import type { DeckCard } from '@/games/types';

/**
 * "Never have I ever…" prompts. Written so the sentence reads naturally after
 * the game title, in both languages.
 */
export const NHIE_DECK: DeckCard[] = [
  { id: 'n1', adult: false, intensity: 'chill', text: { en: 'Never have I ever fallen asleep at a party.', fr: 'Je ne me suis jamais endormi en soirée.' } },
  { id: 'n2', adult: false, intensity: 'chill', text: { en: 'Never have I ever pretended to know a song I had never heard.', fr: 'Je n’ai jamais fait semblant de connaître une chanson que je n’avais jamais entendue.' } },
  { id: 'n3', adult: false, intensity: 'chill', text: { en: 'Never have I ever sent a message to the wrong person.', fr: 'Je n’ai jamais envoyé un message à la mauvaise personne.' } },
  { id: 'n4', adult: false, intensity: 'chill', text: { en: 'Never have I ever lied about my age.', fr: 'Je n’ai jamais menti sur mon âge.' } },
  { id: 'n5', adult: false, intensity: 'chill', text: { en: 'Never have I ever cried watching a cartoon.', fr: 'Je n’ai jamais pleuré devant un dessin animé.' } },
  { id: 'n6', adult: false, intensity: 'chill', text: { en: 'Never have I ever googled myself.', fr: 'Je ne me suis jamais cherché sur Google.' } },
  { id: 'n7', adult: false, intensity: 'chill', text: { en: 'Never have I ever broken something and blamed someone else.', fr: 'Je n’ai jamais cassé un truc en accusant quelqu’un d’autre.' } },
  { id: 'n8', adult: false, intensity: 'chill', text: { en: 'Never have I ever stalked an ex on social media.', fr: 'Je n’ai jamais espionné un ex sur les réseaux.' } },
  { id: 'n9', adult: false, intensity: 'party', text: { en: 'Never have I ever thrown up in a taxi.', fr: 'Je n’ai jamais vomi dans un taxi.' } },
  { id: 'n10', adult: false, intensity: 'party', text: { en: 'Never have I ever woken up somewhere and had no idea how I got there.', fr: 'Je ne me suis jamais réveillé quelque part sans savoir comment j’y étais arrivé.' } },
  { id: 'n11', adult: false, intensity: 'party', text: { en: 'Never have I ever called in sick when I was just hungover.', fr: 'Je n’ai jamais posé un jour de maladie juste pour une gueule de bois.' } },
  { id: 'n12', adult: false, intensity: 'party', text: { en: 'Never have I ever kissed someone in this room.', fr: 'Je n’ai jamais embrassé quelqu’un dans cette pièce.' } },
  { id: 'n13', adult: false, intensity: 'party', text: { en: 'Never have I ever been thrown out of a bar.', fr: 'Je ne me suis jamais fait sortir d’un bar.' } },
  { id: 'n14', adult: false, intensity: 'party', text: { en: 'Never have I ever lied to get out of a date.', fr: 'Je n’ai jamais menti pour annuler un rendez-vous.' } },
  { id: 'n15', adult: false, intensity: 'party', text: { en: 'Never have I ever texted my ex after midnight.', fr: 'Je n’ai jamais écrit à mon ex après minuit.' } },
  { id: 'n16', adult: false, intensity: 'party', text: { en: 'Never have I ever sung karaoke completely sober.', fr: 'Je n’ai jamais fait un karaoké totalement sobre.' } },
  { id: 'n17', adult: false, intensity: 'party', text: { en: 'Never have I ever pretended to like a gift I hated.', fr: 'Je n’ai jamais fait semblant d’aimer un cadeau que je détestais.' } },
  { id: 'n18', adult: false, intensity: 'party', text: { en: 'Never have I ever ghosted someone.', fr: 'Je n’ai jamais ghosté quelqu’un.' } },
  { id: 'n19', adult: false, intensity: 'party', text: { en: 'Never have I ever cheated at a board game.', fr: 'Je n’ai jamais triché à un jeu de société.' } },
  { id: 'n20', adult: false, intensity: 'party', text: { en: 'Never have I ever been in a screaming argument in public.', fr: 'Je n’ai jamais eu une engueulade en pleine rue.' } },
  { id: 'n21', adult: false, intensity: 'party', text: { en: 'Never have I ever stolen something from a hotel room.', fr: 'Je n’ai jamais volé quelque chose dans une chambre d’hôtel.' } },
  { id: 'n22', adult: false, intensity: 'party', text: { en: 'Never have I ever lied on my CV.', fr: 'Je n’ai jamais menti sur mon CV.' } },
  { id: 'n23', adult: false, intensity: 'party', text: { en: 'Never have I ever eaten food off the floor and said nothing.', fr: 'Je n’ai jamais mangé un truc tombé par terre sans le dire.' } },
  { id: 'n24', adult: false, intensity: 'party', text: { en: 'Never have I ever faked an accent for a whole conversation.', fr: 'Je n’ai jamais pris un faux accent pendant toute une conversation.' } },
  { id: 'n25', adult: false, intensity: 'party', text: { en: 'Never have I ever been caught singing in the car.', fr: 'Je ne me suis jamais fait surprendre en train de chanter en voiture.' } },
  { id: 'n26', adult: false, intensity: 'wild', text: { en: 'Never have I ever lost a whole night of memories.', fr: 'Je n’ai jamais perdu le souvenir de toute une nuit.' } },
  { id: 'n27', adult: false, intensity: 'wild', text: { en: 'Never have I ever been dumped by text.', fr: 'Je ne me suis jamais fait larguer par SMS.' } },
  { id: 'n28', adult: false, intensity: 'wild', text: { en: 'Never have I ever crashed a party I was not invited to.', fr: 'Je ne me suis jamais incrusté à une fête sans être invité.' } },
  { id: 'n29', adult: false, intensity: 'wild', text: { en: 'Never have I ever had a crush on a friend’s partner.', fr: 'Je n’ai jamais eu un faible pour le/la partenaire d’un ami.' } },
  { id: 'n30', adult: false, intensity: 'wild', text: { en: 'Never have I ever kept a secret from everyone in this room.', fr: 'Je n’ai jamais gardé un secret pour tout le monde dans cette pièce.' } },
  { id: 'n31', adult: false, intensity: 'wild', text: { en: 'Never have I ever cried in a nightclub bathroom.', fr: 'Je n’ai jamais pleuré dans les toilettes d’une boîte.' } },
  { id: 'n32', adult: false, intensity: 'wild', text: { en: 'Never have I ever been arrested.', fr: 'Je ne me suis jamais fait arrêter par la police.' } },
  { id: 'n33', adult: false, intensity: 'wild', text: { en: 'Never have I ever spent a night in a place I would rather not name.', fr: 'Je n’ai jamais passé une nuit dans un endroit que je préfère ne pas nommer.' } },
  { id: 'n34', adult: false, intensity: 'party', text: { en: 'Never have I ever unfollowed someone out of jealousy.', fr: 'Je n’ai jamais unfollow quelqu’un par jalousie.' } },
  { id: 'n35', adult: false, intensity: 'party', text: { en: 'Never have I ever binged a whole series in one day.', fr: 'Je n’ai jamais englouti une série entière en une journée.' } },
  { id: 'n36', adult: false, intensity: 'chill', text: { en: 'Never have I ever forgotten a close friend’s birthday.', fr: 'Je n’ai jamais oublié l’anniversaire d’un ami proche.' } },
  { id: 'n37', adult: false, intensity: 'chill', text: { en: 'Never have I ever fallen over in front of a crowd.', fr: 'Je ne suis jamais tombé devant une foule.' } },
  { id: 'n38', adult: false, intensity: 'party', text: { en: 'Never have I ever gone home with the wrong coat.', fr: 'Je ne suis jamais rentré chez moi avec le mauvais manteau.' } },
  { id: 'n39', adult: false, intensity: 'party', text: { en: 'Never have I ever pretended to be on the phone to avoid someone.', fr: 'Je n’ai jamais fait semblant d’être au téléphone pour éviter quelqu’un.' } },
  { id: 'n40', adult: false, intensity: 'wild', text: { en: 'Never have I ever kept something I found and never gave it back.', fr: 'Je n’ai jamais gardé un objet trouvé sans le rendre.' } },

  // ------------------------------------------------------------- 18+ deck ---
  { id: 's1', adult: true, intensity: 'wild', text: { en: 'Never have I ever had a one night stand.', fr: 'Je n’ai jamais eu de coup d’un soir.' } },
  { id: 's2', adult: true, intensity: 'wild', text: { en: 'Never have I ever sent a nude.', fr: 'Je n’ai jamais envoyé de nude.' } },
  { id: 's3', adult: true, intensity: 'wild', text: { en: 'Never have I ever faked it.', fr: 'Je n’ai jamais simulé.' } },
  { id: 's4', adult: true, intensity: 'wild', text: { en: 'Never have I ever hooked up with someone I met that same night.', fr: 'Je n’ai jamais couché avec quelqu’un rencontré le soir même.' } },
  { id: 's5', adult: true, intensity: 'wild', text: { en: 'Never have I ever kissed two people in one night.', fr: 'Je n’ai jamais embrassé deux personnes dans la même soirée.' } },
  { id: 's6', adult: true, intensity: 'wild', text: { en: 'Never have I ever been caught in the act.', fr: 'Je ne me suis jamais fait surprendre en pleine action.' } },
  { id: 's7', adult: true, intensity: 'wild', text: { en: 'Never have I ever used a dating app while in a relationship.', fr: 'Je n’ai jamais utilisé une appli de rencontre en couple.' } },
  { id: 's8', adult: true, intensity: 'wild', text: { en: 'Never have I ever had a crush on someone in this room.', fr: 'Je n’ai jamais eu un faible pour quelqu’un dans cette pièce.' } },
  { id: 's9', adult: true, intensity: 'wild', text: { en: 'Never have I ever lied about how many people I have slept with.', fr: 'Je n’ai jamais menti sur mon nombre de partenaires.' } },
  { id: 's10', adult: true, intensity: 'wild', text: { en: 'Never have I ever done it somewhere I could have been caught.', fr: 'Je ne l’ai jamais fait dans un endroit où j’aurais pu être surpris.' } },
  { id: 's11', adult: true, intensity: 'wild', text: { en: 'Never have I ever kept a toy in my bedside drawer.', fr: 'Je n’ai jamais gardé un jouet dans ma table de nuit.' } },
  { id: 's12', adult: true, intensity: 'wild', text: { en: 'Never have I ever gone back to an ex for one more night.', fr: 'Je ne suis jamais retourné voir un ex pour une nuit de plus.' } },
  { id: 's13', adult: true, intensity: 'wild', text: { en: 'Never have I ever left before they woke up.', fr: 'Je ne suis jamais parti avant son réveil.' } },
  { id: 's14', adult: true, intensity: 'wild', text: { en: 'Never have I ever had a crush on a colleague.', fr: 'Je n’ai jamais eu un faible pour un collègue.' } },
  { id: 's15', adult: true, intensity: 'wild', text: { en: 'Never have I ever screenshotted a conversation to show my friends.', fr: 'Je n’ai jamais fait une capture d’écran d’une conversation pour la montrer à mes amis.' } },
];
