import type { DeckCard } from '@/games/types';

/**
 * Two decks that share one shape. `needsPlayer` cards contain {player}, which
 * the engine swaps for a random other player from the party.
 */

export const TRUTHS: DeckCard[] = [
  { id: 't1', adult: false, intensity: 'chill', text: { en: 'What is the last lie you told?', fr: 'Quel est le dernier mensonge que tu as raconté ?' } },
  { id: 't2', adult: false, intensity: 'chill', text: { en: 'What is the most embarrassing thing in your search history?', fr: 'Quelle est la chose la plus gênante dans ton historique de recherche ?' } },
  { id: 't3', adult: false, intensity: 'chill', text: { en: 'How much money do you have in your account right now, roughly?', fr: 'Combien d’argent as-tu sur ton compte là, à peu près ?' } },
  { id: 't4', adult: false, intensity: 'chill', text: { en: 'What is a compliment you gave that you did not mean at all?', fr: 'Quel compliment as-tu fait sans y croire une seconde ?' } },
  { id: 't5', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'What was your very first impression of {player}?', fr: 'Quelle a été ta toute première impression de {player} ?' } },
  { id: 't6', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'Rate {player} out of ten. Out loud. No hiding.', fr: 'Note {player} sur dix. À voix haute. Pas d’échappatoire.' } },
  { id: 't7', adult: false, intensity: 'party', text: { en: 'Who in this room would you call first from jail?', fr: 'Qui appellerais-tu en premier depuis le poste de police ?' } },
  { id: 't8', adult: false, intensity: 'party', text: { en: 'What is the worst thing you have ever said to a family member?', fr: 'Quelle est la pire chose que tu as dite à un membre de ta famille ?' } },
  { id: 't9', adult: false, intensity: 'party', text: { en: 'Show the last photo you took. No swiping first.', fr: 'Montre la dernière photo que tu as prise. Sans faire défiler avant.' } },
  { id: 't10', adult: false, intensity: 'party', text: { en: 'What is the pettiest reason you have ever ended a friendship?', fr: 'Quelle est la raison la plus mesquine pour laquelle tu as coupé une amitié ?' } },
  { id: 't11', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'What is one thing you would change about {player}?', fr: 'Quelle est la seule chose que tu changerais chez {player} ?' } },
  { id: 't12', adult: false, intensity: 'party', text: { en: 'What is the biggest secret you are keeping from your parents?', fr: 'Quel est le plus gros secret que tu caches à tes parents ?' } },
  { id: 't13', adult: false, intensity: 'party', text: { en: 'Read out your last three messages to the person at the top of your chats.', fr: 'Lis tes trois derniers messages à la personne en haut de tes conversations.' } },
  { id: 't14', adult: false, intensity: 'party', text: { en: 'What is the most childish thing you still do?', fr: 'Quelle est la chose la plus puérile que tu fais encore ?' } },
  { id: 't15', adult: false, intensity: 'party', text: { en: 'Have you ever pretended to like someone to get something? Explain.', fr: 'As-tu déjà fait semblant d’apprécier quelqu’un pour obtenir quelque chose ? Explique.' } },
  { id: 't16', adult: false, intensity: 'party', text: { en: 'What is the worst job you have ever had, and why exactly?', fr: 'Quel est le pire job que tu as eu, et pourquoi exactement ?' } },
  { id: 't17', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'Who is more likely to end up rich: you or {player}? Justify it.', fr: 'Qui finira riche : toi ou {player} ? Justifie.' } },
  { id: 't18', adult: false, intensity: 'wild', text: { en: 'What is the worst thing you have done that you never got caught for?', fr: 'Quelle est la pire chose que tu as faite sans jamais te faire prendre ?' } },
  { id: 't19', adult: false, intensity: 'wild', text: { en: 'Who in this room have you talked about behind their back? What did you say?', fr: 'De qui dans cette pièce as-tu parlé dans le dos ? Qu’as-tu dit ?' } },
  { id: 't20', adult: false, intensity: 'wild', text: { en: 'What is the most money you have wasted on something stupid?', fr: 'Quelle est la plus grosse somme que tu as claquée pour rien ?' } },
  { id: 't21', adult: false, intensity: 'wild', text: { en: 'Have you ever ghosted someone here? Come clean.', fr: 'As-tu déjà ghosté quelqu’un ici ? Avoue.' } },
  { id: 't22', adult: false, intensity: 'wild', text: { en: 'What is the last thing you cried about?', fr: 'Quelle est la dernière chose qui t’a fait pleurer ?' } },
  { id: 't23', adult: false, intensity: 'wild', text: { en: 'Which of your friendships here is closest to being over?', fr: 'Laquelle de tes amitiés ici est la plus proche de la fin ?' } },
  { id: 't24', adult: false, intensity: 'party', text: { en: 'What is your most irrational fear? No laughing at the answer.', fr: 'Quelle est ta peur la plus irrationnelle ? On ne rit pas de la réponse.' } },
  { id: 't25', adult: false, intensity: 'party', text: { en: 'Who do you stalk the most online?', fr: 'Qui espionnes-tu le plus en ligne ?' } },
  { id: 't26', adult: false, intensity: 'party', text: { en: 'What is the last thing you regret sending?', fr: 'Quelle est la dernière chose que tu regrettes d’avoir envoyée ?' } },
  { id: 't27', adult: false, intensity: 'party', text: { en: 'Which of your exes would you take back tonight if they asked?', fr: 'Lequel de tes ex reprendrais-tu ce soir s’il te le demandait ?' } },
  { id: 't28', adult: false, intensity: 'chill', text: { en: 'What is a talent you fake having?', fr: 'Quel talent fais-tu semblant d’avoir ?' } },
  { id: 't29', adult: false, intensity: 'chill', text: { en: 'What is your most overused excuse?', fr: 'Quelle est ton excuse la plus réutilisée ?' } },
  { id: 't30', adult: false, intensity: 'wild', text: { en: 'What is something you have never told anyone in this room?', fr: 'Quelle est une chose que tu n’as jamais dite à personne ici ?' } },

  // ------------------------------------------------------------- 18+ ---
  { id: 'ts1', adult: true, intensity: 'wild', text: { en: 'What is your body count? Rounded honestly.', fr: 'Combien de partenaires ? Arrondi honnêtement.' } },
  { id: 'ts2', adult: true, intensity: 'wild', text: { en: 'Where is the riskiest place you have hooked up?', fr: 'Quel est l’endroit le plus risqué où tu l’as fait ?' } },
  { id: 'ts3', adult: true, intensity: 'wild', needsPlayer: true, text: { en: 'If you had to sleep with {player} or nobody ever again, which?', fr: 'Coucher avec {player} ou plus jamais personne : lequel ?' } },
  { id: 'ts4', adult: true, intensity: 'wild', text: { en: 'What is the worst sex you have ever had, and why?', fr: 'Quel est ton pire souvenir au lit, et pourquoi ?' } },
  { id: 'ts5', adult: true, intensity: 'wild', text: { en: 'Describe your type in this room without naming names.', fr: 'Décris ton genre de personne dans cette pièce sans citer de nom.' } },
  { id: 'ts6', adult: true, intensity: 'wild', text: { en: 'What is a fantasy you have never told a partner about?', fr: 'Quel fantasme n’as-tu jamais avoué à un partenaire ?' } },
  { id: 'ts7', adult: true, intensity: 'wild', text: { en: 'Have you ever faked it? With whom, roughly?', fr: 'As-tu déjà simulé ? Avec qui, en gros ?' } },
  { id: 'ts8', adult: true, intensity: 'wild', text: { en: 'What is the last thing you searched that you would not want projected here?', fr: 'Quelle est ta dernière recherche que tu ne voudrais pas projeter ici ?' } },
  { id: 'ts9', adult: true, intensity: 'wild', text: { en: 'Who was the last person you thought about that way?', fr: 'À qui as-tu pensé de cette façon la dernière fois ?' } },
  { id: 'ts10', adult: true, intensity: 'wild', needsPlayer: true, text: { en: 'Rate {player} as a kisser. You have to guess.', fr: 'Note {player} comme embrasseur. Tu dois deviner.' } },
  { id: 'ts11', adult: true, intensity: 'wild', text: { en: 'Have you ever crossed a line while in a relationship?', fr: 'As-tu déjà franchi une ligne en étant en couple ?' } },
  { id: 'ts12', adult: true, intensity: 'wild', text: { en: 'What is the biggest age gap you have been with?', fr: 'Quel est le plus grand écart d’âge que tu as connu ?' } },
];

export const DARES: DeckCard[] = [
  { id: 'd1', adult: false, intensity: 'chill', text: { en: 'Speak in an accent until your next turn. Fail and drink.', fr: 'Parle avec un accent jusqu’à ton prochain tour. Tu craques, tu bois.' } },
  { id: 'd2', adult: false, intensity: 'chill', text: { en: 'Let the group post any emoji they want as your next story.', fr: 'Laisse le groupe poster l’emoji de son choix en story.' } },
  { id: 'd3', adult: false, intensity: 'chill', needsPlayer: true, text: { en: 'Do your best impression of {player}. They judge it.', fr: 'Fais ta meilleure imitation de {player}. C’est lui qui juge.' } },
  { id: 'd4', adult: false, intensity: 'party', text: { en: 'Call the last number you dialled and sing them happy birthday.', fr: 'Appelle le dernier numéro composé et chante-lui joyeux anniversaire.' } },
  { id: 'd5', adult: false, intensity: 'party', text: { en: 'Let the person on your left read out one of your messages, their choice.', fr: 'Laisse ton voisin de gauche lire un de tes messages, à son choix.' } },
  { id: 'd6', adult: false, intensity: 'party', text: { en: 'Swap an item of clothing with the player across from you.', fr: 'Échange un vêtement avec le joueur en face de toi.' } },
  { id: 'd7', adult: false, intensity: 'party', text: { en: 'Do twenty push-ups or drink twice.', fr: 'Vingt pompes ou tu bois double.' } },
  { id: 'd8', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'Give {player} a genuine compliment. If it sounds fake, you drink.', fr: 'Fais un vrai compliment à {player}. S’il sonne faux, tu bois.' } },
  { id: 'd9', adult: false, intensity: 'party', text: { en: 'Let the group choose your new profile picture for one hour.', fr: 'Laisse le groupe choisir ta photo de profil pour une heure.' } },
  { id: 'd10', adult: false, intensity: 'party', text: { en: 'Talk without using the letter A until your next turn.', fr: 'Parle sans utiliser la lettre A jusqu’à ton prochain tour.' } },
  { id: 'd11', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'Let {player} draw on your face with whatever is on the table.', fr: 'Laisse {player} te dessiner sur le visage avec ce qui traîne sur la table.' } },
  { id: 'd12', adult: false, intensity: 'party', text: { en: 'Do your worst dance move for fifteen seconds. Everyone watches.', fr: 'Sors ton pire pas de danse pendant quinze secondes. Tout le monde regarde.' } },
  { id: 'd13', adult: false, intensity: 'party', text: { en: 'Text your mother something absurd but harmless. Show the screen.', fr: 'Écris un truc absurde mais inoffensif à ta mère. Montre l’écran.' } },
  { id: 'd14', adult: false, intensity: 'party', text: { en: 'Let the group scroll your camera roll for ten seconds.', fr: 'Laisse le groupe faire défiler ta galerie pendant dix secondes.' } },
  { id: 'd15', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'Swap seats with {player} and imitate them until your next turn.', fr: 'Échange ta place avec {player} et imite-le jusqu’à ton prochain tour.' } },
  { id: 'd16', adult: false, intensity: 'party', text: { en: 'Say the alphabet backwards. One mistake, one drink.', fr: 'Récite l’alphabet à l’envers. Une erreur, une gorgée.' } },
  { id: 'd17', adult: false, intensity: 'wild', text: { en: 'Let the group send one message from your phone. They pick the words, you pick who.', fr: 'Laisse le groupe envoyer un message depuis ton téléphone. Ils choisissent les mots, tu choisis le destinataire.' } },
  { id: 'd18', adult: false, intensity: 'wild', text: { en: 'Post the ugliest selfie you can take, no deleting for an hour.', fr: 'Poste le selfie le plus moche possible, sans le supprimer pendant une heure.' } },
  { id: 'd19', adult: false, intensity: 'wild', needsPlayer: true, text: { en: 'Let {player} pick your next three drinks.', fr: 'Laisse {player} choisir tes trois prochains verres.' } },
  { id: 'd20', adult: false, intensity: 'wild', text: { en: 'Down whatever is in your glass right now.', fr: 'Finis ce qu’il y a dans ton verre, maintenant.' } },
  { id: 'd21', adult: false, intensity: 'party', text: { en: 'Do an ad for the nearest object as if you were selling it on TV.', fr: 'Fais une pub pour l’objet le plus proche comme si tu le vendais à la télé.' } },
  { id: 'd22', adult: false, intensity: 'party', text: { en: 'Let the group give you a nickname for the rest of the night.', fr: 'Laisse le groupe te donner un surnom pour le reste de la soirée.' } },
  { id: 'd23', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'Sit on the floor at {player}’s feet until your next turn.', fr: 'Assieds-toi par terre aux pieds de {player} jusqu’à ton prochain tour.' } },
  { id: 'd24', adult: false, intensity: 'chill', text: { en: 'Balance something on your head until your next turn.', fr: 'Garde un objet en équilibre sur ta tête jusqu’à ton prochain tour.' } },
  { id: 'd25', adult: false, intensity: 'wild', text: { en: 'Let the person to your right slap your hand as hard as they want. Or drink three.', fr: 'Laisse ton voisin de droite te taper la main aussi fort qu’il veut. Ou bois trois gorgées.' } },
  { id: 'd26', adult: false, intensity: 'party', text: { en: 'Speak only in questions until your next turn.', fr: 'Ne parle qu’avec des questions jusqu’à ton prochain tour.' } },
  { id: 'd27', adult: false, intensity: 'party', text: { en: 'Read the last thing you wrote in your notes app out loud.', fr: 'Lis à voix haute la dernière note que tu as écrite.' } },
  { id: 'd28', adult: false, intensity: 'party', needsPlayer: true, text: { en: 'Trade phones with {player} for two minutes. No deleting first.', fr: 'Échange ton téléphone avec {player} pendant deux minutes. Sans rien supprimer avant.' } },

  // ------------------------------------------------------------- 18+ ---
  { id: 'ds1', adult: true, intensity: 'wild', needsPlayer: true, text: { en: 'Kiss {player} or drink four.', fr: 'Embrasse {player} ou bois quatre gorgées.' } },
  { id: 'ds2', adult: true, intensity: 'wild', text: { en: 'Remove one item of clothing of your choice.', fr: 'Enlève un vêtement de ton choix.' } },
  { id: 'ds3', adult: true, intensity: 'wild', needsPlayer: true, text: { en: 'Give {player} a thirty second shoulder massage.', fr: 'Fais un massage d’épaules de trente secondes à {player}.' } },
  { id: 'ds4', adult: true, intensity: 'wild', text: { en: 'Demonstrate your signature move. Fully clothed, obviously.', fr: 'Démontre ton mouvement signature. Habillé, évidemment.' } },
  { id: 'ds5', adult: true, intensity: 'wild', needsPlayer: true, text: { en: 'Whisper something filthy in {player}’s ear. Only they hear it.', fr: 'Chuchote quelque chose de cochon à l’oreille de {player}. Lui seul l’entend.' } },
  { id: 'ds6', adult: true, intensity: 'wild', text: { en: 'Send a flirty message to the third person in your chat list.', fr: 'Envoie un message aguicheur à la troisième personne de tes conversations.' } },
  { id: 'ds7', adult: true, intensity: 'wild', needsPlayer: true, text: { en: 'Let {player} write anything they want on your arm.', fr: 'Laisse {player} écrire ce qu’il veut sur ton bras.' } },
  { id: 'ds8', adult: true, intensity: 'wild', text: { en: 'Describe the last time out loud. Two sentences minimum.', fr: 'Décris la dernière fois à voix haute. Deux phrases minimum.' } },
  { id: 'ds9', adult: true, intensity: 'wild', needsPlayer: true, text: { en: 'Sit on {player}’s lap until your next turn.', fr: 'Assieds-toi sur les genoux de {player} jusqu’à ton prochain tour.' } },
  { id: 'ds10', adult: true, intensity: 'wild', text: { en: 'Show the group the last person you looked up on a dating app.', fr: 'Montre au groupe la dernière personne que tu as regardée sur une appli de rencontre.' } },
];
