import type { DeckCard } from '@/games/types';

/**
 * Short enough to fit a bingo square on a phone. Everything here is something
 * that genuinely happens at every party, which is the joke.
 */
export const BINGO_DECK: DeckCard[] = [
  { id: 'b1', adult: false, intensity: 'chill', text: { en: 'Someone spills a drink', fr: 'Quelqu’un renverse son verre' } },
  { id: 'b2', adult: false, intensity: 'chill', text: { en: 'The music gets changed mid-song', fr: 'On change la musique en plein morceau' } },
  { id: 'b3', adult: false, intensity: 'chill', text: { en: 'Someone takes a photo nobody agreed to', fr: 'Quelqu’un prend une photo sans demander' } },
  { id: 'b4', adult: false, intensity: 'chill', text: { en: 'A group photo goes wrong', fr: 'Une photo de groupe rate' } },
  { id: 'b5', adult: false, intensity: 'chill', text: { en: 'Someone talks about work', fr: 'Quelqu’un parle du boulot' } },
  { id: 'b6', adult: false, intensity: 'chill', text: { en: 'The snacks run out', fr: 'Les snacks sont finis' } },
  { id: 'b7', adult: false, intensity: 'chill', text: { en: 'Someone shows a video to the whole room', fr: 'Quelqu’un montre une vidéo à toute la pièce' } },
  { id: 'b8', adult: false, intensity: 'chill', text: { en: 'A phone hits 5% battery', fr: 'Un téléphone tombe à 5 %' } },
  { id: 'b9', adult: false, intensity: 'chill', text: { en: 'Someone brings up their star sign', fr: 'Quelqu’un parle de son signe astro' } },
  { id: 'b10', adult: false, intensity: 'chill', text: { en: 'Two people talk over each other for a minute', fr: 'Deux personnes se coupent la parole une minute' } },
  { id: 'b11', adult: false, intensity: 'chill', text: { en: 'Someone reheats food at midnight', fr: 'Quelqu’un réchauffe à manger à minuit' } },
  { id: 'b12', adult: false, intensity: 'chill', text: { en: 'A pet becomes the centre of attention', fr: 'Un animal devient le centre de l’attention' } },
  { id: 'b13', adult: false, intensity: 'party', text: { en: 'Someone says "one more and I go home"', fr: 'Quelqu’un dit « un dernier et je rentre »' } },
  { id: 'b14', adult: false, intensity: 'party', text: { en: 'Someone starts a dance nobody joins', fr: 'Quelqu’un lance une danse que personne ne suit' } },
  { id: 'b15', adult: false, intensity: 'party', text: { en: 'The neighbours are mentioned', fr: 'On parle des voisins' } },
  { id: 'b16', adult: false, intensity: 'party', text: { en: 'Someone tells the same story twice', fr: 'Quelqu’un raconte deux fois la même histoire' } },
  { id: 'b17', adult: false, intensity: 'party', text: { en: 'A drink gets abandoned and lost', fr: 'Un verre est abandonné puis perdu' } },
  { id: 'b18', adult: false, intensity: 'party', text: { en: 'Someone texts their ex', fr: 'Quelqu’un écrit à son ex' } },
  { id: 'b19', adult: false, intensity: 'party', text: { en: 'A serious debate about nothing', fr: 'Un débat très sérieux sur rien' } },
  { id: 'b20', adult: false, intensity: 'party', text: { en: 'Someone sings badly and loudly', fr: 'Quelqu’un chante mal et fort' } },
  { id: 'b21', adult: false, intensity: 'party', text: { en: 'A shot is proposed', fr: 'Quelqu’un propose un shot' } },
  { id: 'b22', adult: false, intensity: 'party', text: { en: 'Somebody goes missing for 20 minutes', fr: 'Quelqu’un disparaît 20 minutes' } },
  { id: 'b23', adult: false, intensity: 'party', text: { en: 'Someone falls asleep sitting up', fr: 'Quelqu’un s’endort assis' } },
  { id: 'b24', adult: false, intensity: 'party', text: { en: 'The lights get turned down', fr: 'On baisse les lumières' } },
  { id: 'b25', adult: false, intensity: 'party', text: { en: 'Someone orders food for the table', fr: 'Quelqu’un commande à manger pour la table' } },
  { id: 'b26', adult: false, intensity: 'party', text: { en: 'A bottle is opened badly', fr: 'Une bouteille est ouverte n’importe comment' } },
  { id: 'b27', adult: false, intensity: 'party', text: { en: 'Someone says "I never get drunk"', fr: 'Quelqu’un dit « je ne suis jamais bourré »' } },
  { id: 'b28', adult: false, intensity: 'party', text: { en: 'The playlist gets hijacked', fr: 'La playlist est détournée' } },
  { id: 'b29', adult: false, intensity: 'party', text: { en: 'Someone shows their camera roll', fr: 'Quelqu’un montre sa galerie photo' } },
  { id: 'b30', adult: false, intensity: 'party', text: { en: 'A game gets suggested and ignored', fr: 'On propose un jeu et personne ne suit' } },
  { id: 'b31', adult: false, intensity: 'party', text: { en: 'Someone gives unsolicited life advice', fr: 'Quelqu’un donne des conseils de vie non demandés' } },
  { id: 'b32', adult: false, intensity: 'party', text: { en: 'Two people discover a mutual friend', fr: 'Deux personnes se découvrent un ami commun' } },
  { id: 'b33', adult: false, intensity: 'party', text: { en: 'Somebody films for their story', fr: 'Quelqu’un filme pour sa story' } },
  { id: 'b34', adult: false, intensity: 'party', text: { en: 'A window gets opened because "it is hot"', fr: 'On ouvre une fenêtre parce qu’« il fait chaud »' } },
  { id: 'b35', adult: false, intensity: 'party', text: { en: 'Someone loses at a game and blames the rules', fr: 'Quelqu’un perd et accuse les règles' } },
  { id: 'b36', adult: false, intensity: 'party', text: { en: 'A taxi gets ordered and cancelled', fr: 'Un taxi est commandé puis annulé' } },
  { id: 'b37', adult: false, intensity: 'wild', text: { en: 'Someone cries', fr: 'Quelqu’un pleure' } },
  { id: 'b38', adult: false, intensity: 'wild', text: { en: 'A secret comes out', fr: 'Un secret sort' } },
  { id: 'b39', adult: false, intensity: 'wild', text: { en: 'Two people disappear together', fr: 'Deux personnes disparaissent ensemble' } },
  { id: 'b40', adult: false, intensity: 'wild', text: { en: 'An argument almost starts', fr: 'Une dispute commence presque' } },
  { id: 'b41', adult: false, intensity: 'wild', text: { en: 'Someone declares undying friendship', fr: 'Quelqu’un déclare une amitié éternelle' } },
  { id: 'b42', adult: false, intensity: 'wild', text: { en: 'Something gets broken', fr: 'Quelque chose se casse' } },
  { id: 'b43', adult: false, intensity: 'wild', text: { en: 'Someone tries to cook at 3am', fr: 'Quelqu’un essaie de cuisiner à 3 h' } },
  { id: 'b44', adult: false, intensity: 'wild', text: { en: 'A confession nobody asked for', fr: 'Une confession que personne n’a demandée' } },
  { id: 'b45', adult: false, intensity: 'wild', text: { en: 'Someone falls over', fr: 'Quelqu’un tombe' } },
  { id: 'b46', adult: false, intensity: 'wild', text: { en: 'The host regrets everything', fr: 'L’hôte regrette tout' } },
  { id: 'b47', adult: false, intensity: 'chill', text: { en: 'Someone asks for the wifi password', fr: 'Quelqu’un demande le code wifi' } },
  { id: 'b48', adult: false, intensity: 'chill', text: { en: 'A charger gets stolen', fr: 'Un chargeur est volé' } },
  { id: 'b49', adult: false, intensity: 'chill', text: { en: 'Someone leaves and comes back', fr: 'Quelqu’un part puis revient' } },
  { id: 'b50', adult: false, intensity: 'chill', text: { en: 'The temperature becomes a topic', fr: 'La température devient un sujet' } },
  { id: 'b51', adult: false, intensity: 'party', text: { en: 'Somebody swears they are not drunk', fr: 'Quelqu’un jure qu’il n’est pas bourré' } },
  { id: 'b52', adult: false, intensity: 'party', text: { en: 'A toast is made', fr: 'On porte un toast' } },
  { id: 'b53', adult: false, intensity: 'party', text: { en: 'Someone changes seats to be next to someone', fr: 'Quelqu’un change de place pour être près de quelqu’un' } },
  { id: 'b54', adult: false, intensity: 'party', text: { en: 'A very old photo resurfaces', fr: 'Une très vieille photo ressort' } },

  // ------------------------------------------------------------- 18+ deck ---
  { id: 'bs1', adult: true, intensity: 'wild', text: { en: 'Someone flirts badly', fr: 'Quelqu’un drague très mal' } },
  { id: 'bs2', adult: true, intensity: 'wild', text: { en: 'Two people kiss', fr: 'Deux personnes s’embrassent' } },
  { id: 'bs3', adult: true, intensity: 'wild', text: { en: 'A dating app gets opened at the table', fr: 'Une appli de rencontre est ouverte à table' } },
  { id: 'bs4', adult: true, intensity: 'wild', text: { en: 'Someone shares far too much detail', fr: 'Quelqu’un donne beaucoup trop de détails' } },
  { id: 'bs5', adult: true, intensity: 'wild', text: { en: 'An ex is described in full', fr: 'Un ex est décrit en détail' } },
  { id: 'bs6', adult: true, intensity: 'wild', text: { en: 'Somebody gets rejected in public', fr: 'Quelqu’un se fait rembarrer en public' } },
];
