import type { DeckCard } from '@/games/types';

/**
 * Questions worth dodging. Every one has to be answerable in a sentence —
 * anything that needs a story is a truth-or-dare card, not this.
 */
export const SIP_DECK: DeckCard[] = [
  { id: 'q1', adult: false, intensity: 'chill', text: { en: 'What is the last lie you told?', fr: 'Quel est le dernier mensonge que tu as dit ?' } },
  { id: 'q2', adult: false, intensity: 'chill', text: { en: 'How much money is in your account right now?', fr: 'Combien y a-t-il sur ton compte là maintenant ?' } },
  { id: 'q3', adult: false, intensity: 'chill', text: { en: 'What is the pettiest reason you have ended a friendship?', fr: 'Quelle est la raison la plus mesquine pour laquelle tu as arrêté une amitié ?' } },
  { id: 'q4', adult: false, intensity: 'chill', text: { en: 'Who in this room do you text the least?', fr: 'À qui dans cette pièce écris-tu le moins ?' } },
  { id: 'q5', adult: false, intensity: 'chill', text: { en: 'What is the last thing you searched for?', fr: 'Quelle est ta dernière recherche internet ?' } },
  { id: 'q6', adult: false, intensity: 'chill', text: { en: 'What is a compliment you gave and did not mean?', fr: 'Quel compliment as-tu fait sans le penser ?' } },
  { id: 'q7', adult: false, intensity: 'chill', text: { en: 'What is the worst gift you have received?', fr: 'Quel est le pire cadeau que tu as reçu ?' } },
  { id: 'q8', adult: false, intensity: 'chill', text: { en: 'How long have you gone without washing your hair?', fr: 'Combien de temps sans te laver les cheveux, au maximum ?' } },
  { id: 'q9', adult: false, intensity: 'chill', text: { en: 'What is the most childish thing you still do?', fr: 'Quelle est la chose la plus enfantine que tu fais encore ?' } },
  { id: 'q10', adult: false, intensity: 'chill', text: { en: 'What is your most useless talent?', fr: 'Quel est ton talent le plus inutile ?' } },
  { id: 'q11', adult: false, intensity: 'chill', text: { en: 'Which of your friends’ habits drives you mad?', fr: 'Quelle habitude d’un de tes amis te rend fou ?' } },
  { id: 'q12', adult: false, intensity: 'chill', text: { en: 'What did you cry about most recently?', fr: 'Pourquoi as-tu pleuré la dernière fois ?' } },
  { id: 'q13', adult: false, intensity: 'party', text: { en: 'Who here would you least want to be stuck in a lift with?', fr: 'Avec qui ici voudrais-tu le moins être coincé dans un ascenseur ?' } },
  { id: 'q14', adult: false, intensity: 'party', text: { en: 'What is the biggest lie you have told your parents?', fr: 'Quel est le plus gros mensonge que tu as dit à tes parents ?' } },
  { id: 'q15', adult: false, intensity: 'party', text: { en: 'What is the worst thing you have said about someone here?', fr: 'Quelle est la pire chose que tu as dite sur quelqu’un ici ?' } },
  { id: 'q16', adult: false, intensity: 'party', text: { en: 'How much did your outfit cost?', fr: 'Combien t’a coûté ta tenue ?' } },
  { id: 'q17', adult: false, intensity: 'party', text: { en: 'What is the last message you deleted?', fr: 'Quel est le dernier message que tu as supprimé ?' } },
  { id: 'q18', adult: false, intensity: 'party', text: { en: 'Who was the last person you looked up online?', fr: 'Qui est la dernière personne que tu as cherchée en ligne ?' } },
  { id: 'q19', adult: false, intensity: 'party', text: { en: 'What is the most embarrassing thing in your bag right now?', fr: 'Quelle est la chose la plus gênante dans ton sac là maintenant ?' } },
  { id: 'q20', adult: false, intensity: 'party', text: { en: 'What have you stolen?', fr: 'Qu’as-tu déjà volé ?' } },
  { id: 'q21', adult: false, intensity: 'party', text: { en: 'Which ex do you still think about?', fr: 'À quel ex penses-tu encore ?' } },
  { id: 'q22', adult: false, intensity: 'party', text: { en: 'What is your worst habit that nobody here knows about?', fr: 'Quelle est ta pire habitude que personne ici ne connaît ?' } },
  { id: 'q23', adult: false, intensity: 'party', text: { en: 'Who here would you swap lives with, and why?', fr: 'Avec qui ici échangerais-tu ta vie, et pourquoi ?' } },
  { id: 'q24', adult: false, intensity: 'party', text: { en: 'What is the meanest nickname you have given someone?', fr: 'Quel est le surnom le plus méchant que tu as donné ?' } },
  { id: 'q25', adult: false, intensity: 'party', text: { en: 'What is the last thing you did that you would not admit to your boss?', fr: 'Qu’as-tu fait récemment que tu n’avouerais pas à ton patron ?' } },
  { id: 'q26', adult: false, intensity: 'party', text: { en: 'Which one of your friendships is basically over?', fr: 'Laquelle de tes amitiés est en réalité terminée ?' } },
  { id: 'q27', adult: false, intensity: 'party', text: { en: 'How many people have you blocked?', fr: 'Combien de personnes as-tu bloquées ?' } },
  { id: 'q28', adult: false, intensity: 'party', text: { en: 'What was your worst haircut and who did it?', fr: 'Quelle a été ta pire coupe de cheveux, et qui l’a faite ?' } },
  { id: 'q29', adult: false, intensity: 'party', text: { en: 'What is the pettiest revenge you have taken?', fr: 'Quelle est la vengeance la plus mesquine que tu aies prise ?' } },
  { id: 'q30', adult: false, intensity: 'party', text: { en: 'What did you last cancel plans for, honestly?', fr: 'Pour quelle vraie raison as-tu annulé la dernière fois ?' } },
  { id: 'q31', adult: false, intensity: 'party', text: { en: 'What is the biggest amount you have lost in one night?', fr: 'Quelle est la plus grosse somme perdue en une soirée ?' } },
  { id: 'q32', adult: false, intensity: 'party', text: { en: 'Who here have you talked about behind their back?', fr: 'De qui ici as-tu parlé dans le dos ?' } },
  { id: 'q33', adult: false, intensity: 'wild', text: { en: 'What is the worst thing you have done and never been caught for?', fr: 'Quelle est la pire chose que tu aies faite sans être pris ?' } },
  { id: 'q34', adult: false, intensity: 'wild', text: { en: 'Who here do you trust the least?', fr: 'En qui ici as-tu le moins confiance ?' } },
  { id: 'q35', adult: false, intensity: 'wild', text: { en: 'What secret are you keeping from someone in this room?', fr: 'Quel secret gardes-tu pour quelqu’un dans cette pièce ?' } },
  { id: 'q36', adult: false, intensity: 'wild', text: { en: 'Have you ever been in love with a friend? Who?', fr: 'As-tu déjà été amoureux d’un ami ? Qui ?' } },
  { id: 'q37', adult: false, intensity: 'wild', text: { en: 'What is the last thing you did that you are genuinely ashamed of?', fr: 'Quelle est la dernière chose dont tu aies vraiment honte ?' } },
  { id: 'q38', adult: false, intensity: 'wild', text: { en: 'Who here would you not invite to your wedding?', fr: 'Qui ici n’inviterais-tu pas à ton mariage ?' } },
  { id: 'q39', adult: false, intensity: 'wild', text: { en: 'What have you lied about tonight?', fr: 'Sur quoi as-tu menti ce soir ?' } },
  { id: 'q40', adult: false, intensity: 'wild', text: { en: 'What is the biggest thing you are hiding from your family?', fr: 'Que caches-tu de plus gros à ta famille ?' } },
  { id: 'q41', adult: false, intensity: 'wild', text: { en: 'Which of your friends’ partners do you dislike?', fr: 'Le/la partenaire de quel ami n’aimes-tu pas ?' } },
  { id: 'q42', adult: false, intensity: 'wild', text: { en: 'Have you ever wished someone here would fail?', fr: 'As-tu déjà souhaité l’échec de quelqu’un ici ?' } },
  { id: 'q43', adult: false, intensity: 'wild', text: { en: 'What would make you cut everyone here off tomorrow?', fr: 'Qu’est-ce qui te ferait couper les ponts avec tous ici demain ?' } },
  { id: 'q44', adult: false, intensity: 'wild', text: { en: 'What do you think people say about you when you leave?', fr: 'Que penses-tu qu’on dise de toi quand tu partes ?' } },
  { id: 'q45', adult: false, intensity: 'chill', text: { en: 'How old were you when you stopped believing in Santa?', fr: 'À quel âge as-tu arrêté de croire au Père Noël ?' } },
  { id: 'q46', adult: false, intensity: 'chill', text: { en: 'What is the longest you have gone without showering?', fr: 'Quel est ton record sans douche ?' } },
  { id: 'q47', adult: false, intensity: 'party', text: { en: 'What is the most you have spent on something stupid?', fr: 'Combien as-tu dépensé de plus pour une bêtise ?' } },
  { id: 'q48', adult: false, intensity: 'party', text: { en: 'Which of your stories is exaggerated?', fr: 'Laquelle de tes anecdotes est exagérée ?' } },
  { id: 'q49', adult: false, intensity: 'party', text: { en: 'Who here gives the worst advice?', fr: 'Qui ici donne les pires conseils ?' } },
  { id: 'q50', adult: false, intensity: 'wild', text: { en: 'What is the one question you hope nobody asks you tonight?', fr: 'Quelle est la question que tu espères que personne ne te posera ce soir ?' } },

  // ------------------------------------------------------------- 18+ deck ---
  { id: 'qs1', adult: true, intensity: 'wild', text: { en: 'How many people have you slept with?', fr: 'Avec combien de personnes as-tu couché ?' } },
  { id: 'qs2', adult: true, intensity: 'wild', text: { en: 'What is the worst place you have hooked up?', fr: 'Quel est le pire endroit où tu as couché ?' } },
  { id: 'qs3', adult: true, intensity: 'wild', text: { en: 'Who here have you thought about that way?', fr: 'À qui ici as-tu déjà pensé de cette façon ?' } },
  { id: 'qs4', adult: true, intensity: 'wild', text: { en: 'What is in your search history you would not read out?', fr: 'Qu’y a-t-il dans ton historique que tu ne lirais pas à voix haute ?' } },
  { id: 'qs5', adult: true, intensity: 'wild', text: { en: 'What is the biggest lie you have told in bed?', fr: 'Quel est le plus gros mensonge dit au lit ?' } },
  { id: 'qs6', adult: true, intensity: 'wild', text: { en: 'Who was your worst hookup, and what went wrong?', fr: 'Quel a été ton pire coup, et qu’est-ce qui a foiré ?' } },
  { id: 'qs7', adult: true, intensity: 'wild', text: { en: 'What is a fantasy you have never told anyone?', fr: 'Quel fantasme n’as-tu jamais avoué ?' } },
  { id: 'qs8', adult: true, intensity: 'wild', text: { en: 'Have you ever cheated? Details.', fr: 'As-tu déjà trompé quelqu’un ? Détails.' } },
  { id: 'qs9', adult: true, intensity: 'wild', text: { en: 'What is your type, and who here fits it?', fr: 'Quel est ton type, et qui ici y correspond ?' } },
  { id: 'qs10', adult: true, intensity: 'wild', text: { en: 'When did you last lie about being single?', fr: 'Quand as-tu menti pour la dernière fois sur ton célibat ?' } },
];
