import type { DeckCard } from '@/games/types';

/**
 * Things to mime. Short noun phrases only — anything longer than four words is
 * unmimeable and just burns the clock. The tame half is here on purpose: a
 * charades round that is one register the whole way through stops being funny
 * after ninety seconds.
 */
export const CHARADES_DECK: DeckCard[] = [
  { id: 'dc1', adult: false, intensity: 'party', text: { en: 'A first kiss that goes wrong', fr: 'Un premier baiser qui rate' } },
  { id: 'dc2', adult: false, intensity: 'party', text: { en: 'Sneaking home at 5am', fr: 'Rentrer en douce à 5 h du matin' } },
  { id: 'dc3', adult: false, intensity: 'party', text: { en: 'Flirting with the bartender', fr: 'Draguer le barman' } },
  { id: 'dc4', adult: false, intensity: 'party', text: { en: 'Getting rejected on the dance floor', fr: 'Se faire rembarrer sur la piste' } },
  { id: 'dc5', adult: false, intensity: 'party', text: { en: 'A very bad slow dance', fr: 'Un slow très raté' } },
  { id: 'dc6', adult: false, intensity: 'party', text: { en: 'Trying to sober up before your parents call', fr: 'Essayer de dessaouler avant l’appel de tes parents' } },
  { id: 'dc7', adult: false, intensity: 'party', text: { en: 'Taking a selfie forty times', fr: 'Prendre un selfie quarante fois' } },
  { id: 'dc8', adult: false, intensity: 'party', text: { en: 'Pretending to enjoy a shot', fr: 'Faire semblant d’aimer un shot' } },
  { id: 'dc9', adult: false, intensity: 'party', text: { en: 'A lap dance nobody asked for', fr: 'Une danse sur les genoux que personne n’a demandée' } },
  { id: 'dc10', adult: false, intensity: 'party', text: { en: 'Getting caught staring', fr: 'Se faire prendre en train de fixer' } },
  { id: 'dc11', adult: false, intensity: 'party', text: { en: 'Texting an ex at midnight', fr: 'Écrire à son ex à minuit' } },
  { id: 'dc12', adult: false, intensity: 'party', text: { en: 'Sending a message to the wrong chat', fr: 'Envoyer un message dans la mauvaise conversation' } },
  { id: 'dc13', adult: false, intensity: 'party', text: { en: 'Fighting a hangover at work', fr: 'Affronter une gueule de bois au boulot' } },
  { id: 'dc14', adult: false, intensity: 'party', text: { en: 'A truly awful pick-up line', fr: 'Une phrase de drague catastrophique' } },
  { id: 'dc15', adult: false, intensity: 'party', text: { en: 'Trying to look sober for a taxi driver', fr: 'Essayer d’avoir l’air sobre devant un chauffeur de taxi' } },
  { id: 'dc16', adult: false, intensity: 'party', text: { en: 'Hiding from someone at a party', fr: 'Se cacher de quelqu’un en soirée' } },
  { id: 'dc17', adult: false, intensity: 'party', text: { en: 'A breakup by text', fr: 'Une rupture par SMS' } },
  { id: 'dc18', adult: false, intensity: 'party', text: { en: 'Losing your phone and finding it', fr: 'Perdre son téléphone puis le retrouver' } },
  { id: 'dc19', adult: false, intensity: 'party', text: { en: 'A dance move you invented at 3am', fr: 'Un pas de danse inventé à 3 h' } },
  { id: 'dc20', adult: false, intensity: 'party', text: { en: 'Meeting the parents for the first time', fr: 'Rencontrer les parents pour la première fois' } },
  { id: 'dc21', adult: true, intensity: 'wild', text: { en: 'A one night stand goodbye', fr: 'L’au revoir d’un coup d’un soir' } },
  { id: 'dc22', adult: true, intensity: 'wild', text: { en: 'Faking it, badly', fr: 'Simuler, très mal' } },
  { id: 'dc23', adult: true, intensity: 'wild', text: { en: 'Buying condoms and knowing the cashier', fr: 'Acheter des préservatifs en connaissant la caissière' } },
  { id: 'dc24', adult: true, intensity: 'wild', text: { en: 'Getting walked in on', fr: 'Se faire surprendre' } },
  { id: 'dc25', adult: true, intensity: 'wild', text: { en: 'A very unsexy striptease', fr: 'Un striptease pas sexy du tout' } },
  { id: 'dc26', adult: true, intensity: 'wild', text: { en: 'Sneaking someone out of the house', fr: 'Faire sortir quelqu’un en douce de la maison' } },
  { id: 'dc27', adult: true, intensity: 'wild', text: { en: 'A tinder date that goes nowhere', fr: 'Un date Tinder qui ne mène à rien' } },
  { id: 'dc28', adult: true, intensity: 'wild', text: { en: 'Explaining a hickey at breakfast', fr: 'Expliquer un suçon au petit-déjeuner' } },
  { id: 'dc29', adult: true, intensity: 'wild', text: { en: 'Reading a very forward message', fr: 'Lire un message très direct' } },
  { id: 'dc30', adult: true, intensity: 'wild', text: { en: 'A hotel room with thin walls', fr: 'Une chambre d’hôtel aux murs fins' } },
  { id: 'dc31', adult: true, intensity: 'wild', text: { en: 'Losing something under the bed', fr: 'Perdre un truc sous le lit' } },
  { id: 'dc32', adult: true, intensity: 'wild', text: { en: 'Trying to be quiet and failing', fr: 'Essayer d’être discret et échouer' } },
  { id: 'dc33', adult: true, intensity: 'wild', text: { en: 'Deleting a photo in a hurry', fr: 'Supprimer une photo en urgence' } },
  { id: 'dc34', adult: true, intensity: 'wild', text: { en: 'Forgetting a name in the morning', fr: 'Oublier un prénom au réveil' } },
  { id: 'dc35', adult: true, intensity: 'wild', text: { en: 'A dramatic bedroom entrance', fr: 'Une entrée dramatique dans la chambre' } },
  { id: 'dc36', adult: true, intensity: 'wild', text: { en: 'Hiding a toy from a guest', fr: 'Cacher un jouet avant l’arrivée d’un invité' } },
  { id: 'dc37', adult: true, intensity: 'wild', text: { en: 'A massage with an agenda', fr: 'Un massage avec une intention' } },
  { id: 'dc38', adult: true, intensity: 'wild', text: { en: 'Pretending to be asleep', fr: 'Faire semblant de dormir' } },
  { id: 'dc39', adult: true, intensity: 'wild', text: { en: 'Explaining yourself to a flatmate', fr: 'S’expliquer devant son colocataire' } },
  { id: 'dc40', adult: true, intensity: 'wild', text: { en: 'A very confident wink', fr: 'Un clin d’œil très confiant' } },
  { id: 'dc41', adult: false, intensity: 'party', text: { en: 'Karaoke you regret immediately', fr: 'Un karaoké regretté immédiatement' } },
  { id: 'dc42', adult: false, intensity: 'party', text: { en: 'A group photo where you blink', fr: 'Une photo de groupe où tu clignes des yeux' } },
  { id: 'dc43', adult: false, intensity: 'party', text: { en: 'Being the designated driver', fr: 'Être le chauffeur désigné' } },
  { id: 'dc44', adult: false, intensity: 'party', text: { en: 'Arguing with a bouncer', fr: 'Discuter avec un videur' } },
  { id: 'dc45', adult: false, intensity: 'party', text: { en: 'Eating a kebab with dignity', fr: 'Manger un kebab avec dignité' } },
  { id: 'dc46', adult: false, intensity: 'party', text: { en: 'Waking up on someone’s sofa', fr: 'Se réveiller sur le canapé de quelqu’un' } },
  { id: 'dc47', adult: false, intensity: 'party', text: { en: 'A drunk phone call to your boss', fr: 'Un appel bourré à ton patron' } },
  { id: 'dc48', adult: false, intensity: 'party', text: { en: 'Dancing to a song you hate', fr: 'Danser sur une chanson que tu détestes' } },
  { id: 'dc49', adult: true, intensity: 'wild', text: { en: 'Rating someone out of ten to their face', fr: 'Noter quelqu’un sur dix en face' } },
  { id: 'dc50', adult: true, intensity: 'wild', text: { en: 'A shower that is not just a shower', fr: 'Une douche qui n’est pas qu’une douche' } },
  { id: 'dc51', adult: true, intensity: 'wild', text: { en: 'Two people and one very small sofa', fr: 'Deux personnes et un canapé très petit' } },
  { id: 'dc52', adult: true, intensity: 'wild', text: { en: 'Explaining a dating app to your grandmother', fr: 'Expliquer une appli de rencontre à ta grand-mère' } },
  { id: 'dc53', adult: false, intensity: 'party', text: { en: 'Pretending to know a song', fr: 'Faire semblant de connaître une chanson' } },
  { id: 'dc54', adult: false, intensity: 'party', text: { en: 'Sneaking a drink into a cinema', fr: 'Faire entrer une boisson au cinéma' } },
  { id: 'dc55', adult: true, intensity: 'wild', text: { en: 'A very awkward morning after', fr: 'Un lendemain matin très gênant' } },
];
