import type { DeckCard } from '@/games/types';

/**
 * Prompts that read naturally after "Who is most likely to…", in both
 * languages. Written to be about the people at the table rather than about
 * strangers — the fun is the arguing, not the card.
 */
export const MLT_DECK: DeckCard[] = [
  { id: 'm1', adult: false, intensity: 'chill', text: { en: '…fall asleep first tonight?', fr: '…s’endormir le premier ce soir ?' } },
  { id: 'm2', adult: false, intensity: 'chill', text: { en: '…become famous for something ridiculous?', fr: '…devenir célèbre pour une raison ridicule ?' } },
  { id: 'm3', adult: false, intensity: 'chill', text: { en: '…forget their own birthday?', fr: '…oublier son propre anniversaire ?' } },
  { id: 'm4', adult: false, intensity: 'chill', text: { en: '…cry at an advert?', fr: '…pleurer devant une pub ?' } },
  { id: 'm5', adult: false, intensity: 'chill', text: { en: '…marry someone they met on holiday?', fr: '…épouser quelqu’un rencontré en vacances ?' } },
  { id: 'm6', adult: false, intensity: 'chill', text: { en: '…start a podcast nobody asked for?', fr: '…lancer un podcast que personne n’a demandé ?' } },
  { id: 'm7', adult: false, intensity: 'chill', text: { en: '…survive the longest in a zombie apocalypse?', fr: '…survivre le plus longtemps à une apocalypse zombie ?' } },
  { id: 'm8', adult: false, intensity: 'chill', text: { en: '…adopt seven cats?', fr: '…adopter sept chats ?' } },
  { id: 'm9', adult: false, intensity: 'chill', text: { en: '…read the terms and conditions?', fr: '…lire les conditions générales ?' } },
  { id: 'm10', adult: false, intensity: 'chill', text: { en: '…move abroad on a whim?', fr: '…partir vivre à l’étranger sur un coup de tête ?' } },
  { id: 'm11', adult: false, intensity: 'chill', text: { en: '…get lost in their own neighbourhood?', fr: '…se perdre dans son propre quartier ?' } },
  { id: 'm12', adult: false, intensity: 'chill', text: { en: '…win a reality TV show?', fr: '…gagner une émission de télé-réalité ?' } },
  { id: 'm13', adult: false, intensity: 'chill', text: { en: '…still be using the same phone in ten years?', fr: '…avoir encore le même téléphone dans dix ans ?' } },
  { id: 'm14', adult: false, intensity: 'chill', text: { en: '…name their child after a fictional character?', fr: '…donner à son enfant le nom d’un personnage de fiction ?' } },
  { id: 'm15', adult: false, intensity: 'chill', text: { en: '…talk to a stranger on a train for two hours?', fr: '…parler deux heures à un inconnu dans le train ?' } },
  { id: 'm16', adult: false, intensity: 'party', text: { en: '…text their ex tonight?', fr: '…écrire à son ex ce soir ?' } },
  { id: 'm17', adult: false, intensity: 'party', text: { en: '…get thrown out of a club?', fr: '…se faire sortir d’une boîte ?' } },
  { id: 'm18', adult: false, intensity: 'party', text: { en: '…start dancing on a table?', fr: '…se mettre à danser sur une table ?' } },
  { id: 'm19', adult: false, intensity: 'party', text: { en: '…lose their phone tonight?', fr: '…perdre son téléphone ce soir ?' } },
  { id: 'm20', adult: false, intensity: 'party', text: { en: '…order the entire menu at 3am?', fr: '…commander la carte entière à 3 h du matin ?' } },
  { id: 'm21', adult: false, intensity: 'party', text: { en: '…cry then laugh within the same minute?', fr: '…pleurer puis rire dans la même minute ?' } },
  { id: 'm22', adult: false, intensity: 'party', text: { en: '…argue with a bouncer and lose?', fr: '…discuter avec un videur et perdre ?' } },
  { id: 'm23', adult: false, intensity: 'party', text: { en: '…post something tonight they regret tomorrow?', fr: '…poster ce soir un truc qu’il regrettera demain ?' } },
  { id: 'm24', adult: false, intensity: 'party', text: { en: '…sing karaoke without being asked?', fr: '…faire un karaoké sans qu’on lui demande ?' } },
  { id: 'm25', adult: false, intensity: 'party', text: { en: '…fight a seagull for their chips?', fr: '…se battre avec une mouette pour ses frites ?' } },
  { id: 'm26', adult: false, intensity: 'party', text: { en: '…miss their flight?', fr: '…rater son avion ?' } },
  { id: 'm27', adult: false, intensity: 'party', text: { en: '…tell their whole life story to a taxi driver?', fr: '…raconter toute sa vie à un chauffeur de taxi ?' } },
  { id: 'm28', adult: false, intensity: 'party', text: { en: '…break something expensive tonight?', fr: '…casser un truc cher ce soir ?' } },
  { id: 'm29', adult: false, intensity: 'party', text: { en: '…get a tattoo on holiday?', fr: '…se faire tatouer en vacances ?' } },
  { id: 'm30', adult: false, intensity: 'party', text: { en: '…be the last one standing tonight?', fr: '…être le dernier debout ce soir ?' } },
  { id: 'm31', adult: false, intensity: 'party', text: { en: '…forget the name of someone they just met, twice?', fr: '…oublier le prénom de quelqu’un deux fois de suite ?' } },
  { id: 'm32', adult: false, intensity: 'party', text: { en: '…start a group chat nobody wants?', fr: '…créer un groupe que personne ne veut ?' } },
  { id: 'm33', adult: false, intensity: 'party', text: { en: '…lie about being on their way?', fr: '…mentir en disant « j’arrive » ?' } },
  { id: 'm34', adult: false, intensity: 'party', text: { en: '…be caught singing in the shower?', fr: '…se faire surprendre en train de chanter sous la douche ?' } },
  { id: 'm35', adult: false, intensity: 'party', text: { en: '…be the reason we all get kicked out?', fr: '…être la raison pour laquelle on se fait tous virer ?' } },
  { id: 'm36', adult: false, intensity: 'party', text: { en: '…spend rent money on a festival ticket?', fr: '…claquer son loyer dans un billet de festival ?' } },
  { id: 'm37', adult: false, intensity: 'party', text: { en: '…fall over completely sober?', fr: '…tomber en étant complètement sobre ?' } },
  { id: 'm38', adult: false, intensity: 'party', text: { en: '…become the group’s designated driver forever?', fr: '…devenir le chauffeur officiel du groupe à vie ?' } },
  { id: 'm39', adult: false, intensity: 'party', text: { en: '…get emotional about a song at 2am?', fr: '…s’émouvoir sur une chanson à 2 h du matin ?' } },
  { id: 'm40', adult: false, intensity: 'party', text: { en: '…swear they are fine when they are absolutely not?', fr: '…jurer que tout va bien alors que non ?' } },
  { id: 'm41', adult: false, intensity: 'wild', text: { en: '…end up in a police station for something stupid?', fr: '…finir au poste pour une bêtise ?' } },
  { id: 'm42', adult: false, intensity: 'wild', text: { en: '…ghost the whole group for a month?', fr: '…ghoster tout le groupe pendant un mois ?' } },
  { id: 'm43', adult: false, intensity: 'wild', text: { en: '…secretly be in love with someone here?', fr: '…être secrètement amoureux de quelqu’un ici ?' } },
  { id: 'm44', adult: false, intensity: 'wild', text: { en: '…read someone else’s messages?', fr: '…lire les messages de quelqu’un d’autre ?' } },
  { id: 'm45', adult: false, intensity: 'wild', text: { en: '…keep a secret about someone in this room?', fr: '…garder un secret sur quelqu’un dans cette pièce ?' } },
  { id: 'm46', adult: false, intensity: 'wild', text: { en: '…quit their job by text?', fr: '…démissionner par SMS ?' } },
  { id: 'm47', adult: false, intensity: 'wild', text: { en: '…lie to our faces and get away with it?', fr: '…nous mentir en face et s’en sortir ?' } },
  { id: 'm48', adult: false, intensity: 'wild', text: { en: '…never tell us about their biggest night out?', fr: '…ne jamais nous raconter sa plus grosse soirée ?' } },
  { id: 'm49', adult: false, intensity: 'wild', text: { en: '…fake an emergency to leave a party?', fr: '…inventer une urgence pour quitter une soirée ?' } },
  { id: 'm50', adult: false, intensity: 'wild', text: { en: '…still be doing exactly this in twenty years?', fr: '…faire encore exactement ça dans vingt ans ?' } },
  { id: 'm51', adult: false, intensity: 'party', text: { en: '…take the last slice without asking?', fr: '…prendre la dernière part sans demander ?' } },
  { id: 'm52', adult: false, intensity: 'party', text: { en: '…leave a party without saying goodbye?', fr: '…partir d’une soirée sans dire au revoir ?' } },
  { id: 'm53', adult: false, intensity: 'party', text: { en: '…start a heated argument about pineapple on pizza?', fr: '…lancer un débat enflammé sur l’ananas sur la pizza ?' } },
  { id: 'm54', adult: false, intensity: 'chill', text: { en: '…become a millionaire and tell nobody?', fr: '…devenir millionnaire sans le dire à personne ?' } },
  { id: 'm55', adult: false, intensity: 'chill', text: { en: '…be a great parent?', fr: '…être un super parent ?' } },
  { id: 'm56', adult: false, intensity: 'chill', text: { en: '…give the best advice and never follow it?', fr: '…donner les meilleurs conseils sans jamais les suivre ?' } },
  { id: 'm57', adult: false, intensity: 'party', text: { en: '…host the messiest party of the year?', fr: '…organiser la soirée la plus chaotique de l’année ?' } },
  { id: 'm58', adult: false, intensity: 'party', text: { en: '…believe an obvious conspiracy theory?', fr: '…croire à une théorie du complot évidente ?' } },
  { id: 'm59', adult: false, intensity: 'wild', text: { en: '…confess something tonight we can never unhear?', fr: '…avouer ce soir un truc qu’on ne pourra jamais oublier ?' } },
  { id: 'm60', adult: false, intensity: 'wild', text: { en: '…be the villain of someone else’s story?', fr: '…être le méchant dans l’histoire de quelqu’un d’autre ?' } },

  // ------------------------------------------------------------- 18+ deck ---
  { id: 'ms1', adult: true, intensity: 'wild', text: { en: '…hook up with a stranger tonight?', fr: '…finir la soirée avec un inconnu ?' } },
  { id: 'ms2', adult: true, intensity: 'wild', text: { en: '…have a secret dating app on their phone right now?', fr: '…avoir une appli de rencontre cachée sur son téléphone là maintenant ?' } },
  { id: 'ms3', adult: true, intensity: 'wild', text: { en: '…send the wrong photo to the wrong person?', fr: '…envoyer la mauvaise photo à la mauvaise personne ?' } },
  { id: 'ms4', adult: true, intensity: 'wild', text: { en: '…sleep with an ex again?', fr: '…recoucher avec un ex ?' } },
  { id: 'ms5', adult: true, intensity: 'wild', text: { en: '…get caught in the act?', fr: '…se faire surprendre en pleine action ?' } },
  { id: 'ms6', adult: true, intensity: 'wild', text: { en: '…have a crush on someone in this room?', fr: '…avoir un faible pour quelqu’un dans cette pièce ?' } },
  { id: 'ms7', adult: true, intensity: 'wild', text: { en: '…kiss two people in one night?', fr: '…embrasser deux personnes dans la même soirée ?' } },
  { id: 'ms8', adult: true, intensity: 'wild', text: { en: '…say yes to a threesome?', fr: '…dire oui à un plan à trois ?' } },
  { id: 'ms9', adult: true, intensity: 'wild', text: { en: '…have the wildest search history?', fr: '…avoir l’historique de recherche le plus salé ?' } },
  { id: 'ms10', adult: true, intensity: 'wild', text: { en: '…flirt with someone completely unavailable?', fr: '…draguer quelqu’un de totalement indisponible ?' } },
  { id: 'ms11', adult: true, intensity: 'wild', text: { en: '…do it in a place they really should not?', fr: '…le faire dans un endroit vraiment pas approprié ?' } },
  { id: 'ms12', adult: true, intensity: 'wild', text: { en: '…keep a full drawer of secrets?', fr: '…garder un tiroir plein de secrets ?' } },
];
