import type { LocalizedText } from '@piccolo/shared';
import type { RoomCard } from '../kit.js';

export interface RankCard extends RoomCard {
  title: LocalizedText;
  /** Exactly five, always. Fewer is trivial, more is unreadable on a phone. */
  items: LocalizedText[];
}

export const RANK_SETS: RankCard[] = [
  { id: 'k1', adult: false, intensity: 'chill', title: { en: 'Best to worst way to spend a Sunday', fr: 'Du meilleur au pire dimanche' }, items: [{ en: 'Long walk', fr: 'Longue balade' }, { en: 'Films in bed', fr: 'Films au lit' }, { en: 'Big lunch out', fr: 'Grand déjeuner dehors' }, { en: 'Cleaning the flat', fr: 'Ménage complet' }, { en: 'Doing nothing at all', fr: 'Absolument rien' }] },
  { id: 'k2', adult: false, intensity: 'chill', title: { en: 'Most to least essential kitchen item', fr: 'Du plus au moins indispensable en cuisine' }, items: [{ en: 'Kettle', fr: 'Bouilloire' }, { en: 'Good knife', fr: 'Bon couteau' }, { en: 'Air fryer', fr: 'Friteuse à air' }, { en: 'Blender', fr: 'Blender' }, { en: 'Garlic press', fr: 'Presse-ail' }] },
  { id: 'k3', adult: false, intensity: 'chill', title: { en: 'Best to worst pizza topping', fr: 'De la meilleure à la pire garniture de pizza' }, items: [{ en: 'Mushrooms', fr: 'Champignons' }, { en: 'Pineapple', fr: 'Ananas' }, { en: 'Anchovies', fr: 'Anchois' }, { en: 'Extra cheese', fr: 'Fromage en plus' }, { en: 'Spicy sausage', fr: 'Saucisse épicée' }] },
  { id: 'k4', adult: false, intensity: 'chill', title: { en: 'Most to least stressful', fr: 'Du plus au moins stressant' }, items: [{ en: 'Public speaking', fr: 'Parler en public' }, { en: 'Moving house', fr: 'Déménager' }, { en: 'A job interview', fr: 'Un entretien d’embauche' }, { en: 'Meeting the parents', fr: 'Rencontrer les parents' }, { en: 'Flying', fr: 'Prendre l’avion' }] },
  { id: 'k5', adult: false, intensity: 'chill', title: { en: 'Best to worst superpower', fr: 'Du meilleur au pire super-pouvoir' }, items: [{ en: 'Flight', fr: 'Voler' }, { en: 'Invisibility', fr: 'Invisibilité' }, { en: 'Time travel', fr: 'Voyage temporel' }, { en: 'Mind reading', fr: 'Lire les pensées' }, { en: 'Super strength', fr: 'Super force' }] },
  { id: 'k6', adult: false, intensity: 'chill', title: { en: 'Most to least useful language to learn', fr: 'De la plus à la moins utile à apprendre' }, items: [{ en: 'Spanish', fr: 'Espagnol' }, { en: 'Mandarin', fr: 'Mandarin' }, { en: 'Arabic', fr: 'Arabe' }, { en: 'German', fr: 'Allemand' }, { en: 'Japanese', fr: 'Japonais' }] },
  { id: 'k7', adult: false, intensity: 'chill', title: { en: 'Best to worst season', fr: 'De la meilleure à la pire saison' }, items: [{ en: 'Spring', fr: 'Printemps' }, { en: 'Summer', fr: 'Été' }, { en: 'Autumn', fr: 'Automne' }, { en: 'Winter', fr: 'Hiver' }, { en: 'That week in November', fr: 'Cette semaine de novembre' }] },
  { id: 'k8', adult: false, intensity: 'chill', title: { en: 'Most to least annoying noise', fr: 'Du plus au moins agaçant' }, items: [{ en: 'Someone chewing', fr: 'Quelqu’un qui mâche' }, { en: 'A car alarm', fr: 'Une alarme de voiture' }, { en: 'A dripping tap', fr: 'Un robinet qui fuit' }, { en: 'A baby crying', fr: 'Un bébé qui pleure' }, { en: 'Loud typing', fr: 'Un clavier bruyant' }] },
  { id: 'k9', adult: false, intensity: 'chill', title: { en: 'Best to worst way to travel', fr: 'Du meilleur au pire moyen de transport' }, items: [{ en: 'Train', fr: 'Train' }, { en: 'Plane', fr: 'Avion' }, { en: 'Road trip', fr: 'Road trip' }, { en: 'Coach', fr: 'Autocar' }, { en: 'Ferry', fr: 'Ferry' }] },
  { id: 'k10', adult: false, intensity: 'chill', title: { en: 'Most to least important in a home', fr: 'Du plus au moins important dans un logement' }, items: [{ en: 'Natural light', fr: 'Lumière naturelle' }, { en: 'Space', fr: 'Espace' }, { en: 'Good neighbours', fr: 'Bons voisins' }, { en: 'Short commute', fr: 'Trajet court' }, { en: 'A balcony', fr: 'Un balcon' }] },
  { id: 'k11', adult: false, intensity: 'party', title: { en: 'Best to worst drink at 2am', fr: 'De la meilleure à la pire boisson à 2 h' }, items: [{ en: 'Water', fr: 'Eau' }, { en: 'Beer', fr: 'Bière' }, { en: 'Tequila', fr: 'Tequila' }, { en: 'Something blue', fr: 'Un truc bleu' }, { en: 'Whatever is left', fr: 'Ce qui reste' }] },
  { id: 'k12', adult: false, intensity: 'party', title: { en: 'Most to least forgivable at a party', fr: 'Du plus au moins pardonnable en soirée' }, items: [{ en: 'Breaking a glass', fr: 'Casser un verre' }, { en: 'Changing the music', fr: 'Changer la musique' }, { en: 'Leaving without saying bye', fr: 'Partir sans dire au revoir' }, { en: 'Finishing the snacks', fr: 'Finir les snacks' }, { en: 'Inviting someone extra', fr: 'Inviter quelqu’un en plus' }] },
  { id: 'k13', adult: false, intensity: 'party', title: { en: 'Best to worst party game', fr: 'Du meilleur au pire jeu de soirée' }, items: [{ en: 'Charades', fr: 'Les mimes' }, { en: 'Never have I ever', fr: 'Je n’ai jamais' }, { en: 'Karaoke', fr: 'Karaoké' }, { en: 'Beer pong', fr: 'Beer pong' }, { en: 'Truth or dare', fr: 'Action ou vérité' }] },
  { id: 'k14', adult: false, intensity: 'party', title: { en: 'Most to least likely to end a night early', fr: 'Du plus au moins susceptible de finir la soirée tôt' }, items: [{ en: 'A lost phone', fr: 'Un téléphone perdu' }, { en: 'An argument', fr: 'Une dispute' }, { en: 'Running out of drinks', fr: 'Plus rien à boire' }, { en: 'A neighbour complaint', fr: 'Une plainte du voisin' }, { en: 'Somebody crying', fr: 'Quelqu’un qui pleure' }] },
  { id: 'k15', adult: false, intensity: 'party', title: { en: 'Most to least attractive quality', fr: 'De la plus à la moins séduisante des qualités' }, items: [{ en: 'Funny', fr: 'Drôle' }, { en: 'Kind', fr: 'Gentil' }, { en: 'Ambitious', fr: 'Ambitieux' }, { en: 'Mysterious', fr: 'Mystérieux' }, { en: 'A good cook', fr: 'Bon cuisinier' }] },
  { id: 'k16', adult: false, intensity: 'party', title: { en: 'Best to worst thing to be famous for', fr: 'Du meilleur au pire motif de célébrité' }, items: [{ en: 'A song', fr: 'Une chanson' }, { en: 'A viral video', fr: 'Une vidéo virale' }, { en: 'A scientific discovery', fr: 'Une découverte scientifique' }, { en: 'A scandal', fr: 'Un scandale' }, { en: 'A sport', fr: 'Un sport' }] },
  { id: 'k17', adult: false, intensity: 'party', title: { en: 'Most to least trustworthy source', fr: 'De la plus à la moins fiable des sources' }, items: [{ en: 'Your mother', fr: 'Ta mère' }, { en: 'A friend of a friend', fr: 'Un ami d’ami' }, { en: 'The internet', fr: 'Internet' }, { en: 'A taxi driver', fr: 'Un chauffeur de taxi' }, { en: 'Your own memory', fr: 'Ta propre mémoire' }] },
  { id: 'k18', adult: false, intensity: 'party', title: { en: 'Most to least embarrassing to be caught doing', fr: 'Du plus au moins gênant à se faire surprendre' }, items: [{ en: 'Singing to yourself', fr: 'Chanter tout seul' }, { en: 'Talking to a pet', fr: 'Parler à un animal' }, { en: 'Practising an argument', fr: 'Répéter une dispute' }, { en: 'Rereading old messages', fr: 'Relire de vieux messages' }, { en: 'Dancing alone', fr: 'Danser seul' }] },
  { id: 'k19', adult: false, intensity: 'wild', title: { en: 'Most to least serious betrayal', fr: 'De la plus à la moins grave trahison' }, items: [{ en: 'Reading their messages', fr: 'Lire ses messages' }, { en: 'Lying about money', fr: 'Mentir sur l’argent' }, { en: 'Telling their secret', fr: 'Raconter son secret' }, { en: 'Flirting with their ex', fr: 'Draguer son ex' }, { en: 'Forgetting their birthday', fr: 'Oublier son anniversaire' }] },
  { id: 'k20', adult: false, intensity: 'wild', title: { en: 'Most to least worth ending a friendship over', fr: 'Du plus au moins digne de rompre une amitié' }, items: [{ en: 'Borrowed money never returned', fr: 'De l’argent jamais rendu' }, { en: 'A lie about you', fr: 'Un mensonge sur toi' }, { en: 'Ghosting for a year', fr: 'Ghoster pendant un an' }, { en: 'Never asking how you are', fr: 'Ne jamais demander comment tu vas' }, { en: 'Dating your ex', fr: 'Sortir avec ton ex' }] },
  { id: 'k21', adult: false, intensity: 'chill', title: { en: 'Best to worst first date', fr: 'Du meilleur au pire premier rendez-vous' }, items: [{ en: 'A long walk', fr: 'Une longue balade' }, { en: 'Dinner', fr: 'Un dîner' }, { en: 'A gallery', fr: 'Une expo' }, { en: 'A bar', fr: 'Un bar' }, { en: 'Bowling', fr: 'Un bowling' }] },
  { id: 'k22', adult: false, intensity: 'chill', title: { en: 'Most to least likely to survive a week alone in the woods', fr: 'Du plus au moins apte à survivre une semaine en forêt' }, items: [{ en: 'A chef', fr: 'Un cuisinier' }, { en: 'A nurse', fr: 'Un infirmier' }, { en: 'A hiker', fr: 'Un randonneur' }, { en: 'A carpenter', fr: 'Un menuisier' }, { en: 'A software developer', fr: 'Un développeur' }] },
  { id: 'k23', adult: false, intensity: 'party', title: { en: 'Best to worst wedding job', fr: 'Du meilleur au pire rôle à un mariage' }, items: [{ en: 'Best man or maid of honour', fr: 'Témoin' }, { en: 'The photographer', fr: 'Le photographe' }, { en: 'The DJ', fr: 'Le DJ' }, { en: 'Doing the speech', fr: 'Faire le discours' }, { en: 'Driving everyone home', fr: 'Ramener tout le monde' }] },
  { id: 'k24', adult: false, intensity: 'party', title: { en: 'Most to least impressive skill', fr: 'De la plus à la moins impressionnante des compétences' }, items: [{ en: 'Playing piano', fr: 'Jouer du piano' }, { en: 'Speaking four languages', fr: 'Parler quatre langues' }, { en: 'Doing a backflip', fr: 'Faire un salto arrière' }, { en: 'Cooking anything from scratch', fr: 'Tout cuisiner de zéro' }, { en: 'Perfect handwriting', fr: 'Une écriture parfaite' }] },
  { id: 'k25', adult: false, intensity: 'chill', title: { en: 'Most to least overrated', fr: 'Du plus au moins surestimé' }, items: [{ en: 'Brunch', fr: 'Le brunch' }, { en: 'New Year’s Eve', fr: 'Le Nouvel An' }, { en: 'Festivals', fr: 'Les festivals' }, { en: 'Beach holidays', fr: 'Les vacances à la plage' }, { en: 'Working from home', fr: 'Le télétravail' }] },

  { id: 'ks1', adult: true, intensity: 'wild', title: { en: 'Most to least acceptable dating red flag', fr: 'Du plus au moins acceptable comme red flag' }, items: [{ en: 'Still texting their ex', fr: 'Écrit encore à son ex' }, { en: 'Never pays', fr: 'Ne paie jamais' }, { en: 'Rude to waiters', fr: 'Malpoli avec les serveurs' }, { en: 'Talks only about work', fr: 'Ne parle que du boulot' }, { en: 'Lives with their parents', fr: 'Vit chez ses parents' }] },
  { id: 'ks2', adult: true, intensity: 'wild', title: { en: 'Most to least private thing to share', fr: 'Du plus au moins intime à partager' }, items: [{ en: 'Your number of partners', fr: 'Ton nombre de partenaires' }, { en: 'Your salary', fr: 'Ton salaire' }, { en: 'Your search history', fr: 'Ton historique' }, { en: 'Your messages', fr: 'Tes messages' }, { en: 'Your weight', fr: 'Ton poids' }] },
];
