import type { LocalizedText } from '@piccolo/shared';
import type { RoomCard } from '../kit.js';

export interface QuizCard extends RoomCard {
  question: LocalizedText;
  /** Four options in a fixed order; `correct` indexes into it. */
  options: LocalizedText[];
  correct: number;
}

/**
 * Four options, one right, nothing that needs a specific country's schooling to
 * answer. Order is shuffled per round on the server, so the correct index here
 * is only the source of truth, never a pattern anyone can learn.
 */
export const QUIZ: QuizCard[] = [
  { id: 'q1', adult: false, intensity: 'chill', correct: 1, question: { en: 'How many bones are in the adult human body?', fr: 'Combien d’os compte le corps humain adulte ?' }, options: [{ en: '186', fr: '186' }, { en: '206', fr: '206' }, { en: '226', fr: '226' }, { en: '246', fr: '246' }] },
  { id: 'q2', adult: false, intensity: 'chill', correct: 2, question: { en: 'Which planet has the most moons?', fr: 'Quelle planète a le plus de lunes ?' }, options: [{ en: 'Jupiter', fr: 'Jupiter' }, { en: 'Neptune', fr: 'Neptune' }, { en: 'Saturn', fr: 'Saturne' }, { en: 'Uranus', fr: 'Uranus' }] },
  { id: 'q3', adult: false, intensity: 'chill', correct: 0, question: { en: 'What is the capital of Australia?', fr: 'Quelle est la capitale de l’Australie ?' }, options: [{ en: 'Canberra', fr: 'Canberra' }, { en: 'Sydney', fr: 'Sydney' }, { en: 'Melbourne', fr: 'Melbourne' }, { en: 'Perth', fr: 'Perth' }] },
  { id: 'q4', adult: false, intensity: 'chill', correct: 3, question: { en: 'Which element has the symbol "K"?', fr: 'Quel élément a pour symbole « K » ?' }, options: [{ en: 'Krypton', fr: 'Krypton' }, { en: 'Calcium', fr: 'Calcium' }, { en: 'Carbon', fr: 'Carbone' }, { en: 'Potassium', fr: 'Potassium' }] },
  { id: 'q5', adult: false, intensity: 'chill', correct: 1, question: { en: 'How many strings does a standard bass guitar have?', fr: 'Combien de cordes a une basse standard ?' }, options: [{ en: 'Three', fr: 'Trois' }, { en: 'Four', fr: 'Quatre' }, { en: 'Five', fr: 'Cinq' }, { en: 'Six', fr: 'Six' }] },
  { id: 'q6', adult: false, intensity: 'chill', correct: 2, question: { en: 'Which country has the longest coastline?', fr: 'Quel pays a le plus long littoral ?' }, options: [{ en: 'Russia', fr: 'La Russie' }, { en: 'Australia', fr: 'L’Australie' }, { en: 'Canada', fr: 'Le Canada' }, { en: 'Indonesia', fr: 'L’Indonésie' }] },
  { id: 'q7', adult: false, intensity: 'chill', correct: 0, question: { en: 'What does "HTTP" stand for?', fr: 'Que signifie « HTTP » ?' }, options: [{ en: 'HyperText Transfer Protocol', fr: 'HyperText Transfer Protocol' }, { en: 'High Transfer Text Protocol', fr: 'High Transfer Text Protocol' }, { en: 'HyperText Transit Program', fr: 'HyperText Transit Program' }, { en: 'Host Transfer Text Protocol', fr: 'Host Transfer Text Protocol' }] },
  { id: 'q8', adult: false, intensity: 'chill', correct: 1, question: { en: 'Which sea is the saltiest?', fr: 'Quelle mer est la plus salée ?' }, options: [{ en: 'The Red Sea', fr: 'La mer Rouge' }, { en: 'The Dead Sea', fr: 'La mer Morte' }, { en: 'The Baltic Sea', fr: 'La mer Baltique' }, { en: 'The Caspian Sea', fr: 'La mer Caspienne' }] },
  { id: 'q9', adult: false, intensity: 'chill', correct: 3, question: { en: 'How many minutes are in a full week?', fr: 'Combien de minutes dans une semaine complète ?' }, options: [{ en: '6 720', fr: '6 720' }, { en: '8 640', fr: '8 640' }, { en: '9 600', fr: '9 600' }, { en: '10 080', fr: '10 080' }] },
  { id: 'q10', adult: false, intensity: 'chill', correct: 2, question: { en: 'Which animal has the longest gestation period?', fr: 'Quel animal a la plus longue gestation ?' }, options: [{ en: 'The blue whale', fr: 'La baleine bleue' }, { en: 'The giraffe', fr: 'La girafe' }, { en: 'The elephant', fr: 'L’éléphant' }, { en: 'The rhinoceros', fr: 'Le rhinocéros' }] },
  { id: 'q11', adult: false, intensity: 'chill', correct: 0, question: { en: 'What is the most spoken first language in the world?', fr: 'Quelle est la langue maternelle la plus parlée au monde ?' }, options: [{ en: 'Mandarin Chinese', fr: 'Le mandarin' }, { en: 'English', fr: 'L’anglais' }, { en: 'Spanish', fr: 'L’espagnol' }, { en: 'Hindi', fr: 'Le hindi' }] },
  { id: 'q12', adult: false, intensity: 'chill', correct: 1, question: { en: 'Which vitamin does sunlight help the body produce?', fr: 'Quelle vitamine le soleil aide-t-il à produire ?' }, options: [{ en: 'Vitamin C', fr: 'La vitamine C' }, { en: 'Vitamin D', fr: 'La vitamine D' }, { en: 'Vitamin B12', fr: 'La vitamine B12' }, { en: 'Vitamin A', fr: 'La vitamine A' }] },
  { id: 'q13', adult: false, intensity: 'chill', correct: 3, question: { en: 'How many keys does a standard piano have?', fr: 'Combien de touches a un piano standard ?' }, options: [{ en: '61', fr: '61' }, { en: '72', fr: '72' }, { en: '76', fr: '76' }, { en: '88', fr: '88' }] },
  { id: 'q14', adult: false, intensity: 'chill', correct: 2, question: { en: 'Which country invented pizza margherita?', fr: 'Quel pays a inventé la pizza margherita ?' }, options: [{ en: 'Greece', fr: 'La Grèce' }, { en: 'France', fr: 'La France' }, { en: 'Italy', fr: 'L’Italie' }, { en: 'Spain', fr: 'L’Espagne' }] },
  { id: 'q15', adult: false, intensity: 'chill', correct: 0, question: { en: 'What is the largest organ in the human body?', fr: 'Quel est le plus grand organe du corps humain ?' }, options: [{ en: 'The skin', fr: 'La peau' }, { en: 'The liver', fr: 'Le foie' }, { en: 'The lungs', fr: 'Les poumons' }, { en: 'The intestines', fr: 'Les intestins' }] },
  { id: 'q16', adult: false, intensity: 'chill', correct: 1, question: { en: 'Which gas do plants absorb from the air?', fr: 'Quel gaz les plantes absorbent-elles dans l’air ?' }, options: [{ en: 'Oxygen', fr: 'L’oxygène' }, { en: 'Carbon dioxide', fr: 'Le dioxyde de carbone' }, { en: 'Nitrogen', fr: 'L’azote' }, { en: 'Helium', fr: 'L’hélium' }] },
  { id: 'q17', adult: false, intensity: 'chill', correct: 3, question: { en: 'How many players are on a football pitch at kick-off?', fr: 'Combien de joueurs sur un terrain de foot au coup d’envoi ?' }, options: [{ en: '18', fr: '18' }, { en: '20', fr: '20' }, { en: '21', fr: '21' }, { en: '22', fr: '22' }] },
  { id: 'q18', adult: false, intensity: 'chill', correct: 2, question: { en: 'What is the currency of Japan?', fr: 'Quelle est la monnaie du Japon ?' }, options: [{ en: 'The won', fr: 'Le won' }, { en: 'The yuan', fr: 'Le yuan' }, { en: 'The yen', fr: 'Le yen' }, { en: 'The baht', fr: 'Le baht' }] },
  { id: 'q19', adult: false, intensity: 'chill', correct: 0, question: { en: 'Which ocean is the deepest?', fr: 'Quel océan est le plus profond ?' }, options: [{ en: 'The Pacific', fr: 'Le Pacifique' }, { en: 'The Atlantic', fr: 'L’Atlantique' }, { en: 'The Indian', fr: 'L’Indien' }, { en: 'The Arctic', fr: 'L’Arctique' }] },
  { id: 'q20', adult: false, intensity: 'chill', correct: 1, question: { en: 'How long is a standard Olympic swimming pool?', fr: 'Quelle est la longueur d’un bassin olympique ?' }, options: [{ en: '25 metres', fr: '25 mètres' }, { en: '50 metres', fr: '50 mètres' }, { en: '75 metres', fr: '75 mètres' }, { en: '100 metres', fr: '100 mètres' }] },
  { id: 'q21', adult: false, intensity: 'party', correct: 2, question: { en: 'Which drink is made from fermented grapes?', fr: 'Quelle boisson est faite de raisin fermenté ?' }, options: [{ en: 'Cider', fr: 'Le cidre' }, { en: 'Beer', fr: 'La bière' }, { en: 'Wine', fr: 'Le vin' }, { en: 'Sake', fr: 'Le saké' }] },
  { id: 'q22', adult: false, intensity: 'party', correct: 0, question: { en: 'What is the main spirit in a mojito?', fr: 'Quel est l’alcool principal d’un mojito ?' }, options: [{ en: 'Rum', fr: 'Le rhum' }, { en: 'Gin', fr: 'Le gin' }, { en: 'Vodka', fr: 'La vodka' }, { en: 'Tequila', fr: 'La tequila' }] },
  { id: 'q23', adult: false, intensity: 'party', correct: 3, question: { en: 'Which country drinks the most coffee per person?', fr: 'Quel pays boit le plus de café par habitant ?' }, options: [{ en: 'Italy', fr: 'L’Italie' }, { en: 'Brazil', fr: 'Le Brésil' }, { en: 'Turkey', fr: 'La Turquie' }, { en: 'Finland', fr: 'La Finlande' }] },
  { id: 'q24', adult: false, intensity: 'party', correct: 1, question: { en: 'How many bubbles are roughly in a bottle of champagne?', fr: 'Combien de bulles environ dans une bouteille de champagne ?' }, options: [{ en: 'About 500 000', fr: 'Environ 500 000' }, { en: 'About 49 million', fr: 'Environ 49 millions' }, { en: 'About 2 million', fr: 'Environ 2 millions' }, { en: 'About 800 million', fr: 'Environ 800 millions' }] },
  { id: 'q25', adult: false, intensity: 'party', correct: 2, question: { en: 'Which of these is not a real cocktail?', fr: 'Lequel n’est pas un vrai cocktail ?' }, options: [{ en: 'Corpse Reviver', fr: 'Corpse Reviver' }, { en: 'Penicillin', fr: 'Penicillin' }, { en: 'Iron Curtain', fr: 'Iron Curtain' }, { en: 'Paper Plane', fr: 'Paper Plane' }] },
  { id: 'q26', adult: false, intensity: 'chill', correct: 0, question: { en: 'Who painted the ceiling of the Sistine Chapel?', fr: 'Qui a peint le plafond de la chapelle Sixtine ?' }, options: [{ en: 'Michelangelo', fr: 'Michel-Ange' }, { en: 'Leonardo da Vinci', fr: 'Léonard de Vinci' }, { en: 'Raphael', fr: 'Raphaël' }, { en: 'Donatello', fr: 'Donatello' }] },
  { id: 'q27', adult: false, intensity: 'chill', correct: 1, question: { en: 'In which year did the first iPhone go on sale?', fr: 'En quelle année le premier iPhone est-il sorti ?' }, options: [{ en: '2005', fr: '2005' }, { en: '2007', fr: '2007' }, { en: '2009', fr: '2009' }, { en: '2010', fr: '2010' }] },
  { id: 'q28', adult: false, intensity: 'chill', correct: 3, question: { en: 'Which city hosted the first modern Olympic Games?', fr: 'Quelle ville a accueilli les premiers Jeux olympiques modernes ?' }, options: [{ en: 'Paris', fr: 'Paris' }, { en: 'London', fr: 'Londres' }, { en: 'Rome', fr: 'Rome' }, { en: 'Athens', fr: 'Athènes' }] },
  { id: 'q29', adult: false, intensity: 'chill', correct: 2, question: { en: 'What is the smallest prime number?', fr: 'Quel est le plus petit nombre premier ?' }, options: [{ en: '0', fr: '0' }, { en: '1', fr: '1' }, { en: '2', fr: '2' }, { en: '3', fr: '3' }] },
  { id: 'q30', adult: false, intensity: 'chill', correct: 0, question: { en: 'Which language has the most native speakers in Africa?', fr: 'Quelle langue compte le plus de locuteurs natifs en Afrique ?' }, options: [{ en: 'Arabic', fr: 'L’arabe' }, { en: 'Swahili', fr: 'Le swahili' }, { en: 'French', fr: 'Le français' }, { en: 'Hausa', fr: 'Le haoussa' }] },
  { id: 'q31', adult: false, intensity: 'chill', correct: 1, question: { en: 'How fast does light travel, roughly?', fr: 'À quelle vitesse voyage la lumière, environ ?' }, options: [{ en: '3 000 km/s', fr: '3 000 km/s' }, { en: '300 000 km/s', fr: '300 000 km/s' }, { en: '30 000 km/s', fr: '30 000 km/s' }, { en: '3 million km/s', fr: '3 millions km/s' }] },
  { id: 'q32', adult: false, intensity: 'chill', correct: 3, question: { en: 'Which of these countries has no coastline?', fr: 'Lequel de ces pays n’a pas de littoral ?' }, options: [{ en: 'Portugal', fr: 'Le Portugal' }, { en: 'Croatia', fr: 'La Croatie' }, { en: 'Denmark', fr: 'Le Danemark' }, { en: 'Hungary', fr: 'La Hongrie' }] },
  { id: 'q33', adult: false, intensity: 'chill', correct: 2, question: { en: 'What is the hardest known natural material?', fr: 'Quel est le matériau naturel le plus dur connu ?' }, options: [{ en: 'Quartz', fr: 'Le quartz' }, { en: 'Titanium', fr: 'Le titane' }, { en: 'Diamond', fr: 'Le diamant' }, { en: 'Granite', fr: 'Le granit' }] },
  { id: 'q34', adult: false, intensity: 'chill', correct: 0, question: { en: 'How many time zones does France have, counting overseas?', fr: 'Combien de fuseaux horaires a la France, outre-mer compris ?' }, options: [{ en: 'Twelve', fr: 'Douze' }, { en: 'Four', fr: 'Quatre' }, { en: 'One', fr: 'Un' }, { en: 'Seven', fr: 'Sept' }] },
  { id: 'q35', adult: false, intensity: 'chill', correct: 1, question: { en: 'Which bird is the fastest in level flight?', fr: 'Quel oiseau est le plus rapide en vol horizontal ?' }, options: [{ en: 'The peregrine falcon', fr: 'Le faucon pèlerin' }, { en: 'The common swift', fr: 'Le martinet noir' }, { en: 'The albatross', fr: 'L’albatros' }, { en: 'The golden eagle', fr: 'L’aigle royal' }] },
  { id: 'q36', adult: false, intensity: 'party', correct: 2, question: { en: 'Which film franchise has grossed the most money?', fr: 'Quelle franchise de films a rapporté le plus ?' }, options: [{ en: 'Star Wars', fr: 'Star Wars' }, { en: 'Harry Potter', fr: 'Harry Potter' }, { en: 'The Marvel Cinematic Universe', fr: 'L’univers Marvel' }, { en: 'James Bond', fr: 'James Bond' }] },
  { id: 'q37', adult: false, intensity: 'party', correct: 0, question: { en: 'Which social network was founded first?', fr: 'Quel réseau social a été fondé en premier ?' }, options: [{ en: 'Facebook', fr: 'Facebook' }, { en: 'Twitter', fr: 'Twitter' }, { en: 'Instagram', fr: 'Instagram' }, { en: 'Snapchat', fr: 'Snapchat' }] },
  { id: 'q38', adult: false, intensity: 'party', correct: 3, question: { en: 'How many episodes are in a standard sitcom season, traditionally?', fr: 'Combien d’épisodes compte traditionnellement une saison de sitcom ?' }, options: [{ en: '8', fr: '8' }, { en: '13', fr: '13' }, { en: '16', fr: '16' }, { en: '22', fr: '22' }] },
  { id: 'q39', adult: false, intensity: 'chill', correct: 1, question: { en: 'What is the chemical formula for table salt?', fr: 'Quelle est la formule chimique du sel de table ?' }, options: [{ en: 'KCl', fr: 'KCl' }, { en: 'NaCl', fr: 'NaCl' }, { en: 'CaCl₂', fr: 'CaCl₂' }, { en: 'NaHCO₃', fr: 'NaHCO₃' }] },
  { id: 'q40', adult: false, intensity: 'chill', correct: 2, question: { en: 'Which country produces the most olive oil?', fr: 'Quel pays produit le plus d’huile d’olive ?' }, options: [{ en: 'Italy', fr: 'L’Italie' }, { en: 'Greece', fr: 'La Grèce' }, { en: 'Spain', fr: 'L’Espagne' }, { en: 'Tunisia', fr: 'La Tunisie' }] },

  { id: 'qs1', adult: true, intensity: 'wild', correct: 1, question: { en: 'Which country was the first to legalise same-sex marriage?', fr: 'Quel pays a légalisé le premier le mariage entre personnes de même sexe ?' }, options: [{ en: 'Canada', fr: 'Le Canada' }, { en: 'The Netherlands', fr: 'Les Pays-Bas' }, { en: 'Spain', fr: 'L’Espagne' }, { en: 'Belgium', fr: 'La Belgique' }] },
  { id: 'qs2', adult: true, intensity: 'wild', correct: 0, question: { en: 'What is the most common reason given for a first date going badly?', fr: 'Quelle est la raison la plus citée d’un premier rendez-vous raté ?' }, options: [{ en: 'Talking only about themselves', fr: 'Ne parler que de soi' }, { en: 'Arriving late', fr: 'Arriver en retard' }, { en: 'Splitting the bill', fr: 'Partager l’addition' }, { en: 'Choosing the venue', fr: 'Le choix du lieu' }] },
  { id: 'qs3', adult: true, intensity: 'wild', correct: 3, question: { en: 'Roughly what share of people admit to reading a partner’s messages?', fr: 'Quelle part des gens admet lire les messages de son partenaire ?' }, options: [{ en: 'About 5%', fr: 'Environ 5 %' }, { en: 'About 15%', fr: 'Environ 15 %' }, { en: 'About 25%', fr: 'Environ 25 %' }, { en: 'About 35%', fr: 'Environ 35 %' }] },
];
