import type { DeckCard } from '@/games/types';

/**
 * The 18+ edition. Two ground rules held the whole deck together while writing
 * it: nothing that needs another person's body without asking them first, and
 * nothing that only works if somebody is too drunk to say no. Chickening out is
 * always on the table — that button is the point.
 */
export const SPICY_TRUTHS: DeckCard[] = [
  { id: 'st1', adult: true, intensity: 'party', text: { en: 'What is your type, honestly?', fr: 'C’est quoi ton type, honnêtement ?' } },
  { id: 'st2', adult: true, intensity: 'party', text: { en: 'Who in this room would you swipe right on?', fr: 'Sur qui dans cette pièce swiperais-tu à droite ?' } },
  { id: 'st3', adult: true, intensity: 'party', text: { en: 'What is the worst pick-up line that has ever worked on you?', fr: 'Quelle est la pire phrase de drague qui a marché sur toi ?' } },
  { id: 'st4', adult: true, intensity: 'party', text: { en: 'How long was your shortest relationship?', fr: 'Quelle a été ta relation la plus courte ?' } },
  { id: 'st5', adult: true, intensity: 'party', text: { en: 'What is the most embarrassing thing you have done to impress someone?', fr: 'Quelle est la chose la plus gênante faite pour impressionner quelqu’un ?' } },
  { id: 'st6', adult: true, intensity: 'party', text: { en: 'Have you ever been caught looking? By whom?', fr: 'T’es-tu déjà fait surprendre en train de regarder ? Par qui ?' } },
  { id: 'st7', adult: true, intensity: 'party', text: { en: 'What is the boldest message you have ever sent?', fr: 'Quel est le message le plus osé que tu as envoyé ?' } },
  { id: 'st8', adult: true, intensity: 'party', text: { en: 'Whose name is in your phone under something you would not read out?', fr: 'Qui est enregistré dans ton téléphone sous un nom que tu ne lirais pas à voix haute ?' } },
  { id: 'st9', adult: true, intensity: 'party', text: { en: 'What is the last thing that made you blush?', fr: 'Qu’est-ce qui t’a fait rougir pour la dernière fois ?' } },
  { id: 'st10', adult: true, intensity: 'party', text: { en: 'Have you ever kissed someone and immediately regretted it?', fr: 'As-tu déjà embrassé quelqu’un et regretté immédiatement ?' } },
  { id: 'st11', adult: true, intensity: 'wild', text: { en: 'How many people have you kissed this year?', fr: 'Combien de personnes as-tu embrassées cette année ?' } },
  { id: 'st12', adult: true, intensity: 'wild', text: { en: 'What is the strangest place you have hooked up?', fr: 'Quel est l’endroit le plus étrange où tu as couché ?' } },
  { id: 'st13', adult: true, intensity: 'wild', text: { en: 'What is a fantasy you have never said out loud?', fr: 'Quel fantasme n’as-tu jamais dit à voix haute ?' } },
  { id: 'st14', adult: true, intensity: 'wild', text: { en: 'Have you ever faked it? Convincingly?', fr: 'As-tu déjà simulé ? De façon convaincante ?' } },
  { id: 'st15', adult: true, intensity: 'wild', text: { en: 'Who was your worst hookup, and what exactly went wrong?', fr: 'Quel a été ton pire coup, et qu’est-ce qui a foiré exactement ?' } },
  { id: 'st16', adult: true, intensity: 'wild', text: { en: 'What is the biggest lie you have told to get someone into bed?', fr: 'Quel est le plus gros mensonge dit pour mettre quelqu’un dans ton lit ?' } },
  { id: 'st17', adult: true, intensity: 'wild', text: { en: 'Have you ever hooked up with a friend? Are they here?', fr: 'As-tu déjà couché avec un ami ? Est-il ici ?' } },
  { id: 'st18', adult: true, intensity: 'wild', text: { en: 'What is the closest you have come to being caught?', fr: 'Quelle est la fois où tu as failli te faire surprendre ?' } },
  { id: 'st19', adult: true, intensity: 'wild', text: { en: 'What is something you like that you would never admit sober?', fr: 'Qu’est-ce que tu aimes et que tu n’avouerais jamais sobre ?' } },
  { id: 'st20', adult: true, intensity: 'wild', text: { en: 'Have you ever cheated, or been cheated on? Which was worse?', fr: 'As-tu déjà trompé, ou été trompé ? Lequel était le pire ?' } },
  { id: 'st21', adult: true, intensity: 'wild', text: { en: 'Who here have you thought about after a night out?', fr: 'À qui ici as-tu pensé après une soirée ?' } },
  { id: 'st22', adult: true, intensity: 'wild', text: { en: 'What is the most you have ever lied about your number?', fr: 'De combien as-tu déjà menti sur ton nombre ?' } },
  { id: 'st23', adult: true, intensity: 'wild', text: { en: 'What is the fastest you have ever gone from meeting to kissing?', fr: 'Quel est ton record entre la rencontre et le baiser ?' } },
  { id: 'st24', adult: true, intensity: 'wild', text: { en: 'What would make you say yes to something you normally would not?', fr: 'Qu’est-ce qui te ferait dire oui à quelque chose que tu refuserais normalement ?' } },
  { id: 'st25', adult: true, intensity: 'wild', text: { en: 'What is the pettiest reason you have turned someone down?', fr: 'Quelle est la raison la plus mesquine pour laquelle tu as dit non à quelqu’un ?' } },
  { id: 'st26', adult: true, intensity: 'wild', text: { en: 'Have you ever kept a photo you should have deleted?', fr: 'As-tu gardé une photo que tu aurais dû supprimer ?' } },
  { id: 'st27', adult: true, intensity: 'wild', text: { en: 'What is your most reliable move, and does it actually work?', fr: 'Quelle est ta technique la plus fiable, et est-ce qu’elle marche vraiment ?' } },
  { id: 'st28', adult: true, intensity: 'wild', text: { en: 'Who is the one that got away, and do you still think about it?', fr: 'Qui est celui/celle que tu as laissé filer, et y penses-tu encore ?' } },
  { id: 'st29', adult: true, intensity: 'wild', text: { en: 'What is the worst thing you have said in the moment?', fr: 'Quelle est la pire chose que tu as dite sur le moment ?' } },
  { id: 'st30', adult: true, intensity: 'wild', text: { en: 'Have you ever left in the middle of the night? Why?', fr: 'As-tu déjà filé en pleine nuit ? Pourquoi ?' } },
  { id: 'st31', adult: true, intensity: 'party', text: { en: 'Who here gives the best flirting energy, and who gives the worst?', fr: 'Qui ici drague le mieux, et qui le plus mal ?' } },
  { id: 'st32', adult: true, intensity: 'party', text: { en: 'What is on your phone right now that you would not want read out?', fr: 'Qu’y a-t-il sur ton téléphone que tu ne voudrais pas voir lu à voix haute ?' } },
  { id: 'st33', adult: true, intensity: 'wild', text: { en: 'Rank everyone here as flatmate, date and partner in crime.', fr: 'Classe tout le monde ici en coloc, date et complice.' } },
  { id: 'st34', adult: true, intensity: 'wild', text: { en: 'What is the one question about your love life you hope nobody asks?', fr: 'Quelle question sur ta vie amoureuse espères-tu que personne ne pose ?' } },
  { id: 'st35', adult: true, intensity: 'wild', text: { en: 'Have you ever said a name and got it wrong?', fr: 'As-tu déjà dit un prénom et t’es trompé ?' } },
];

export const SPICY_DARES: DeckCard[] = [
  { id: 'sd1', adult: true, intensity: 'party', text: { en: 'Read out the last message you sent to someone you fancy.', fr: 'Lis le dernier message envoyé à quelqu’un qui te plaît.' } },
  { id: 'sd2', adult: true, intensity: 'party', text: { en: 'Let the table write your dating app bio. It goes up for one hour.', fr: 'Laisse la table écrire ta bio d’appli de rencontre. Elle reste une heure.' } },
  { id: 'sd3', adult: true, intensity: 'party', needsPlayer: true, text: { en: 'Do your best flirty impression of {player}.', fr: 'Fais ton imitation la plus aguicheuse de {player}.' } },
  { id: 'sd4', adult: true, intensity: 'party', text: { en: 'Give {player} a genuine compliment about how they look. Mean it.', fr: 'Fais un vrai compliment à {player} sur son allure. Sincèrement.' }, needsPlayer: true },
  { id: 'sd5', adult: true, intensity: 'party', text: { en: 'Say your most-used pick-up line to the person on your left.', fr: 'Sors ta phrase de drague la plus utilisée à la personne à ta gauche.' } },
  { id: 'sd6', adult: true, intensity: 'party', text: { en: 'Send a single flame emoji to the third person in your chat list.', fr: 'Envoie une seule flamme à la troisième personne de ta liste de discussions.' } },
  { id: 'sd7', adult: true, intensity: 'party', text: { en: 'Show the table your most flattering photo of yourself and explain it.', fr: 'Montre à la table ta photo la plus avantageuse et explique-la.' } },
  { id: 'sd8', adult: true, intensity: 'party', text: { en: 'Whisper something you find attractive about {player} to them. Only them.', fr: 'Chuchote à {player} ce que tu trouves attirant chez lui/elle. À lui/elle seulement.' }, needsPlayer: true },
  { id: 'sd9', adult: true, intensity: 'party', text: { en: 'Take off one item of clothing of your choice. Socks count, once.', fr: 'Enlève un vêtement de ton choix. Les chaussettes comptent, une fois.' } },
  { id: 'sd10', adult: true, intensity: 'party', text: { en: 'Do your best slow-motion hair flip. Commit fully.', fr: 'Fais ton meilleur mouvement de cheveux au ralenti. À fond.' } },
  { id: 'sd11', adult: true, intensity: 'party', text: { en: 'Text your ex a single word of the table’s choosing.', fr: 'Envoie à ton ex un seul mot choisi par la table.' } },
  { id: 'sd12', adult: true, intensity: 'party', text: { en: 'Describe your last kiss in three words.', fr: 'Décris ton dernier baiser en trois mots.' } },
  { id: 'sd13', adult: true, intensity: 'wild', text: { en: 'Let {player} choose one contact and send them a heart. No context.', fr: 'Laisse {player} choisir un contact et envoie-lui un cœur. Sans contexte.' }, needsPlayer: true },
  { id: 'sd14', adult: true, intensity: 'wild', text: { en: 'Sit on the floor and act out your worst date in sixty seconds.', fr: 'Assieds-toi par terre et rejoue ton pire rendez-vous en soixante secondes.' } },
  { id: 'sd15', adult: true, intensity: 'wild', text: { en: 'Let the table pick a nickname for you. It sticks until you leave.', fr: 'Laisse la table te donner un surnom. Il tient jusqu’à ton départ.' } },
  { id: 'sd16', adult: true, intensity: 'wild', text: { en: 'Give {player} a shoulder massage for thirty seconds — if they say yes.', fr: 'Masse les épaules de {player} pendant trente secondes — s’il/elle est d’accord.' }, needsPlayer: true },
  { id: 'sd17', adult: true, intensity: 'wild', text: { en: 'Whisper one thing you would never say sober to the person on your right.', fr: 'Chuchote à la personne à ta droite une chose que tu ne dirais jamais sobre.' } },
  { id: 'sd18', adult: true, intensity: 'wild', text: { en: 'Let {player} read out one message from your phone. They choose the chat.', fr: 'Laisse {player} lire un message de ton téléphone. Il/elle choisit la conversation.' }, needsPlayer: true },
  { id: 'sd19', adult: true, intensity: 'wild', text: { en: 'Demonstrate your dance move for when you want someone to notice you.', fr: 'Montre le pas de danse que tu sors quand tu veux qu’on te remarque.' } },
  { id: 'sd20', adult: true, intensity: 'wild', text: { en: 'Say out loud which two people here would make the best couple, and why.', fr: 'Dis à voix haute quelles deux personnes ici feraient le meilleur couple, et pourquoi.' } },
  { id: 'sd21', adult: true, intensity: 'wild', text: { en: 'Blow a kiss to everyone at the table, one at a time, straight-faced.', fr: 'Envoie un baiser à chacun à table, un par un, sans rire.' } },
  { id: 'sd22', adult: true, intensity: 'wild', text: { en: 'Swap one item of clothing with {player}, if they agree.', fr: 'Échange un vêtement avec {player}, s’il/elle est d’accord.' }, needsPlayer: true },
  { id: 'sd23', adult: true, intensity: 'wild', text: { en: 'Let the table dictate one message you send to anyone. You may veto once.', fr: 'Laisse la table dicter un message que tu envoies à qui elle veut. Un veto autorisé.' } },
  { id: 'sd24', adult: true, intensity: 'wild', text: { en: 'Recreate the face you make when someone you like walks in.', fr: 'Refais la tête que tu fais quand quelqu’un qui te plaît entre.' } },
  { id: 'sd25', adult: true, intensity: 'wild', text: { en: 'Confess which card in this deck you were hoping not to get.', fr: 'Avoue quelle carte de ce deck tu espérais ne pas tirer.' } },
  { id: 'sd26', adult: true, intensity: 'wild', text: { en: 'Hold eye contact with {player} for twenty seconds. No laughing.', fr: 'Soutiens le regard de {player} pendant vingt secondes. Interdit de rire.' }, needsPlayer: true },
  { id: 'sd27', adult: true, intensity: 'wild', text: { en: 'Tell {player} one thing you have always wanted to say to them.', fr: 'Dis à {player} une chose que tu as toujours voulu lui dire.' }, needsPlayer: true },
  { id: 'sd28', adult: true, intensity: 'wild', text: { en: 'Give the table your honest rating of your own flirting, out of ten.', fr: 'Donne à la table ta note honnête sur ta propre drague, sur dix.' } },
  { id: 'sd29', adult: true, intensity: 'party', text: { en: 'Post a photo of your drink with a caption the table writes.', fr: 'Poste une photo de ton verre avec une légende écrite par la table.' } },
  { id: 'sd30', adult: true, intensity: 'party', text: { en: 'Do the walk you do when you know someone is watching.', fr: 'Fais la démarche que tu prends quand tu sais qu’on te regarde.' } },
];
