import type { DeckCard } from '@/games/types';

/**
 * Rapid fire: every question has to be answerable in under five seconds, or the
 * minute is gone in three cards. Anything that needs a story belongs in
 * sip-or-spill.
 */
export const HOT_SEAT_DECK: DeckCard[] = [
  { id: 'h1', adult: false, intensity: 'party', text: { en: 'Best kisser you have ever had?', fr: 'La meilleure personne que tu aies embrassée ?' } },
  { id: 'h2', adult: false, intensity: 'party', text: { en: 'Last person you stalked online?', fr: 'La dernière personne que tu as stalkée en ligne ?' } },
  { id: 'h3', adult: false, intensity: 'party', text: { en: 'Biggest regret from last year?', fr: 'Ton plus gros regret de l’an dernier ?' } },
  { id: 'h4', adult: false, intensity: 'party', text: { en: 'Who here would you never live with?', fr: 'Avec qui ici ne vivrais-tu jamais ?' } },
  { id: 'h5', adult: false, intensity: 'party', text: { en: 'Worst date, one sentence?', fr: 'Ton pire rendez-vous, en une phrase ?' } },
  { id: 'h6', adult: false, intensity: 'party', text: { en: 'Something you have lied about tonight?', fr: 'Un truc sur lequel tu as menti ce soir ?' } },
  { id: 'h7', adult: false, intensity: 'party', text: { en: 'Most attractive celebrity, no hesitation?', fr: 'La célébrité la plus attirante, sans hésiter ?' } },
  { id: 'h8', adult: false, intensity: 'party', text: { en: 'Last thing you cried about?', fr: 'La dernière chose qui t’a fait pleurer ?' } },
  { id: 'h9', adult: false, intensity: 'party', text: { en: 'How much is in your account, to the nearest hundred?', fr: 'Combien sur ton compte, à cent près ?' } },
  { id: 'h10', adult: false, intensity: 'party', text: { en: 'Who here talks the most nonsense?', fr: 'Qui ici raconte le plus n’importe quoi ?' } },
  { id: 'h11', adult: false, intensity: 'party', text: { en: 'Something you have stolen?', fr: 'Quelque chose que tu as volé ?' } },
  { id: 'h12', adult: false, intensity: 'party', text: { en: 'Last thing you searched for?', fr: 'Ta dernière recherche ?' } },
  { id: 'h13', adult: false, intensity: 'party', text: { en: 'Who here would you call from a police station?', fr: 'Qui appellerais-tu depuis un commissariat ?' } },
  { id: 'h14', adult: false, intensity: 'party', text: { en: 'Worst habit nobody knows about?', fr: 'Ta pire habitude que personne ne connaît ?' } },
  { id: 'h15', adult: false, intensity: 'party', text: { en: 'Biggest lie on your CV?', fr: 'Le plus gros mensonge de ton CV ?' } },
  { id: 'h16', adult: false, intensity: 'party', text: { en: 'Who here is the most annoying, on a bad day?', fr: 'Qui ici est le plus pénible, un mauvais jour ?' } },
  { id: 'h17', adult: false, intensity: 'party', text: { en: 'Last message you deleted?', fr: 'Le dernier message que tu as supprimé ?' } },
  { id: 'h18', adult: false, intensity: 'party', text: { en: 'Number of exes you would take back?', fr: 'Combien d’ex reprendrais-tu ?' } },
  { id: 'h19', adult: false, intensity: 'party', text: { en: 'Most money wasted in one night?', fr: 'Le plus d’argent claqué en une soirée ?' } },
  { id: 'h20', adult: false, intensity: 'party', text: { en: 'Something you judge people for?', fr: 'Un truc pour lequel tu juges les gens ?' } },
  { id: 'h21', adult: false, intensity: 'wild', text: { en: 'Who here have you had a crush on?', fr: 'Sur qui ici as-tu eu un faible ?' } },
  { id: 'h22', adult: false, intensity: 'wild', text: { en: 'Worst thing you have said behind someone’s back?', fr: 'La pire chose dite dans le dos de quelqu’un ?' } },
  { id: 'h23', adult: false, intensity: 'wild', text: { en: 'A secret you are keeping right now?', fr: 'Un secret que tu gardes là maintenant ?' } },
  { id: 'h24', adult: false, intensity: 'wild', text: { en: 'Who here do you trust the least?', fr: 'En qui ici as-tu le moins confiance ?' } },
  { id: 'h25', adult: false, intensity: 'wild', text: { en: 'Something you have done and never admitted?', fr: 'Un truc fait et jamais avoué ?' } },
  { id: 'h26', adult: false, intensity: 'wild', text: { en: 'Which friendship here is fake?', fr: 'Quelle amitié ici est fausse ?' } },
  { id: 'h27', adult: false, intensity: 'wild', text: { en: 'Who would you cut off tomorrow with no explanation?', fr: 'Qui couperais-tu demain sans explication ?' } },
  { id: 'h28', adult: false, intensity: 'wild', text: { en: 'Biggest thing you hide from your family?', fr: 'Ce que tu caches le plus à ta famille ?' } },
  { id: 'h29', adult: false, intensity: 'wild', text: { en: 'Have you ever wished someone here would fail?', fr: 'As-tu déjà souhaité l’échec de quelqu’un ici ?' } },
  { id: 'h30', adult: false, intensity: 'wild', text: { en: 'What do people get wrong about you?', fr: 'Qu’est-ce que les gens comprennent mal chez toi ?' } },
  { id: 'h31', adult: true, intensity: 'wild', text: { en: 'Number of people you have slept with?', fr: 'Avec combien de personnes as-tu couché ?' } },
  { id: 'h32', adult: true, intensity: 'wild', text: { en: 'Strangest place you have hooked up?', fr: 'L’endroit le plus étrange où tu as couché ?' } },
  { id: 'h33', adult: true, intensity: 'wild', text: { en: 'Who here would you say yes to?', fr: 'À qui ici dirais-tu oui ?' } },
  { id: 'h34', adult: true, intensity: 'wild', text: { en: 'Have you faked it? How often?', fr: 'As-tu déjà simulé ? Souvent ?' } },
  { id: 'h35', adult: true, intensity: 'wild', text: { en: 'One fantasy, out loud, now?', fr: 'Un fantasme, à voix haute, maintenant ?' } },
  { id: 'h36', adult: true, intensity: 'wild', text: { en: 'Best and worst you have ever had?', fr: 'Le meilleur et le pire que tu aies eu ?' } },
  { id: 'h37', adult: true, intensity: 'wild', text: { en: 'Ever hooked up with a friend? Name?', fr: 'Déjà couché avec un ami ? Prénom ?' } },
  { id: 'h38', adult: true, intensity: 'wild', text: { en: 'Something in your bedside drawer?', fr: 'Un truc dans ta table de nuit ?' } },
  { id: 'h39', adult: true, intensity: 'wild', text: { en: 'Have you ever cheated?', fr: 'As-tu déjà trompé quelqu’un ?' } },
  { id: 'h40', adult: true, intensity: 'wild', text: { en: 'Nastiest thing you have said in the moment?', fr: 'La pire chose dite sur le moment ?' } },
  { id: 'h41', adult: true, intensity: 'wild', text: { en: 'Who is the last person you thought about that way?', fr: 'La dernière personne à qui tu as pensé de cette façon ?' } },
  { id: 'h42', adult: true, intensity: 'wild', text: { en: 'What is your type, in three words?', fr: 'Ton type, en trois mots ?' } },
  { id: 'h43', adult: true, intensity: 'wild', text: { en: 'Shortest time from meeting to bed?', fr: 'Ton record entre la rencontre et le lit ?' } },
  { id: 'h44', adult: true, intensity: 'wild', text: { en: 'Anything you have deleted from your camera roll?', fr: 'Un truc supprimé de ta galerie ?' } },
  { id: 'h45', adult: true, intensity: 'wild', text: { en: 'Ever said the wrong name?', fr: 'Déjà dit le mauvais prénom ?' } },
  { id: 'h46', adult: false, intensity: 'party', text: { en: 'Who here is the best liar?', fr: 'Qui ici est le meilleur menteur ?' } },
  { id: 'h47', adult: false, intensity: 'party', text: { en: 'Something you are pretending to like?', fr: 'Un truc que tu fais semblant d’aimer ?' } },
  { id: 'h48', adult: false, intensity: 'party', text: { en: 'Last person you ignored on purpose?', fr: 'La dernière personne que tu as ignorée exprès ?' } },
  { id: 'h49', adult: false, intensity: 'party', text: { en: 'Worst thing about being you?', fr: 'Le pire dans le fait d’être toi ?' } },
  { id: 'h50', adult: false, intensity: 'party', text: { en: 'Who here would you swap lives with?', fr: 'Avec qui ici échangerais-tu ta vie ?' } },
  { id: 'h51', adult: false, intensity: 'wild', text: { en: 'What would ruin your reputation if it got out?', fr: 'Qu’est-ce qui ruinerait ta réputation si ça sortait ?' } },
  { id: 'h52', adult: false, intensity: 'wild', text: { en: 'Who in your family would be most disappointed in you?', fr: 'Qui dans ta famille serait le plus déçu de toi ?' } },
  { id: 'h53', adult: false, intensity: 'party', text: { en: 'One thing you would change about someone here?', fr: 'Une chose que tu changerais chez quelqu’un ici ?' } },
  { id: 'h54', adult: false, intensity: 'party', text: { en: 'Most embarrassing thing on your playlist?', fr: 'Le truc le plus gênant sur ta playlist ?' } },
  { id: 'h55', adult: false, intensity: 'wild', text: { en: 'Are you happy? Really?', fr: 'Es-tu heureux ? Vraiment ?' } },
];
