import type { DeckCard } from '@/games/types';

/**
 * Every card has to be answerable with one name from the table — that is the
 * whole mechanic. "Who here…" rather than "what would you…".
 */
export const PARANOIA_DECK: DeckCard[] = [
  { id: 'p1', adult: false, intensity: 'chill', text: { en: 'Who here would you call at 4am?', fr: 'Qui appellerais-tu à 4 h du matin ?' } },
  { id: 'p2', adult: false, intensity: 'chill', text: { en: 'Who here is the worst driver?', fr: 'Qui conduit le plus mal ?' } },
  { id: 'p3', adult: false, intensity: 'chill', text: { en: 'Who here would survive a week in the woods?', fr: 'Qui survivrait une semaine en forêt ?' } },
  { id: 'p4', adult: false, intensity: 'chill', text: { en: 'Who here gives the best hugs?', fr: 'Qui fait les meilleurs câlins ?' } },
  { id: 'p5', adult: false, intensity: 'chill', text: { en: 'Who here is secretly the most competitive?', fr: 'Qui est secrètement le plus compétitif ?' } },
  { id: 'p6', adult: false, intensity: 'chill', text: { en: 'Who here would you trust with your passwords?', fr: 'À qui confierais-tu tes mots de passe ?' } },
  { id: 'p7', adult: false, intensity: 'chill', text: { en: 'Who here talks the most and says the least?', fr: 'Qui parle le plus et dit le moins ?' } },
  { id: 'p8', adult: false, intensity: 'chill', text: { en: 'Who here will be rich first?', fr: 'Qui sera riche en premier ?' } },
  { id: 'p9', adult: false, intensity: 'chill', text: { en: 'Who here is the worst at texting back?', fr: 'Qui répond le plus mal aux messages ?' } },
  { id: 'p10', adult: false, intensity: 'chill', text: { en: 'Who here has the best taste in music?', fr: 'Qui a les meilleurs goûts musicaux ?' } },
  { id: 'p11', adult: false, intensity: 'chill', text: { en: 'Who here would make the best flatmate?', fr: 'Qui ferait le meilleur colocataire ?' } },
  { id: 'p12', adult: false, intensity: 'chill', text: { en: 'Who here needs a nap right now?', fr: 'Qui a besoin d’une sieste là maintenant ?' } },
  { id: 'p13', adult: false, intensity: 'party', text: { en: 'Who here is going to be the messiest tonight?', fr: 'Qui sera le plus en vrac ce soir ?' } },
  { id: 'p14', adult: false, intensity: 'party', text: { en: 'Who here is the biggest liar?', fr: 'Qui est le plus gros menteur ?' } },
  { id: 'p15', adult: false, intensity: 'party', text: { en: 'Who here would you never lend money to?', fr: 'À qui ne prêterais-tu jamais d’argent ?' } },
  { id: 'p16', adult: false, intensity: 'party', text: { en: 'Who here has the worst dating history?', fr: 'Qui a le pire historique amoureux ?' } },
  { id: 'p17', adult: false, intensity: 'party', text: { en: 'Who here is the most likely to start a fight?', fr: 'Qui est le plus susceptible de chercher la bagarre ?' } },
  { id: 'p18', adult: false, intensity: 'party', text: { en: 'Who here checks their phone too much?', fr: 'Qui regarde trop son téléphone ?' } },
  { id: 'p19', adult: false, intensity: 'party', text: { en: 'Who here would sell the group out first?', fr: 'Qui balancerait le groupe en premier ?' } },
  { id: 'p20', adult: false, intensity: 'party', text: { en: 'Who here is the fakest when they are annoyed?', fr: 'Qui est le plus faux quand il est agacé ?' } },
  { id: 'p21', adult: false, intensity: 'party', text: { en: 'Who here is the best kisser, going on rumours alone?', fr: 'Qui embrasse le mieux, rien qu’en se fiant aux rumeurs ?' } },
  { id: 'p22', adult: false, intensity: 'party', text: { en: 'Who here would you leave behind in a heist?', fr: 'Qui abandonnerais-tu pendant un braquage ?' } },
  { id: 'p23', adult: false, intensity: 'party', text: { en: 'Who here has the worst hidden habit?', fr: 'Qui a la pire habitude cachée ?' } },
  { id: 'p24', adult: false, intensity: 'party', text: { en: 'Who here takes the best photos of themselves and the worst of you?', fr: 'Qui se prend en photo parfaitement et te rate systématiquement ?' } },
  { id: 'p25', adult: false, intensity: 'party', text: { en: 'Who here could not keep a secret for a week?', fr: 'Qui ne garderait pas un secret une semaine ?' } },
  { id: 'p26', adult: false, intensity: 'party', text: { en: 'Who here is the most dramatic?', fr: 'Qui est le plus dramatique ?' } },
  { id: 'p27', adult: false, intensity: 'party', text: { en: 'Who here would you swap phones with for a day?', fr: 'Avec qui échangerais-tu ton téléphone pour une journée ?' } },
  { id: 'p28', adult: false, intensity: 'party', text: { en: 'Who here has the most embarrassing crush?', fr: 'Qui a le crush le plus gênant ?' } },
  { id: 'p29', adult: false, intensity: 'party', text: { en: 'Who here is the group’s biggest flirt?', fr: 'Qui est le plus dragueur du groupe ?' } },
  { id: 'p30', adult: false, intensity: 'party', text: { en: 'Who here would cry first watching a sad film?', fr: 'Qui pleurerait en premier devant un film triste ?' } },
  { id: 'p31', adult: false, intensity: 'wild', text: { en: 'Who here do you find most attractive?', fr: 'Qui trouves-tu le plus attirant ?' } },
  { id: 'p32', adult: false, intensity: 'wild', text: { en: 'Who here would you never date?', fr: 'Avec qui ne sortirais-tu jamais ?' } },
  { id: 'p33', adult: false, intensity: 'wild', text: { en: 'Who here is hiding something tonight?', fr: 'Qui cache quelque chose ce soir ?' } },
  { id: 'p34', adult: false, intensity: 'wild', text: { en: 'Who here do you like the least, honestly?', fr: 'Qui aimes-tu le moins, honnêtement ?' } },
  { id: 'p35', adult: false, intensity: 'wild', text: { en: 'Who here has changed the most, and not for the better?', fr: 'Qui a le plus changé, et pas en mieux ?' } },
  { id: 'p36', adult: false, intensity: 'wild', text: { en: 'Who here would you trust with a secret that could ruin you?', fr: 'À qui confierais-tu un secret qui pourrait te détruire ?' } },
  { id: 'p37', adult: false, intensity: 'wild', text: { en: 'Who here is probably in love with someone in this room?', fr: 'Qui est probablement amoureux de quelqu’un dans cette pièce ?' } },
  { id: 'p38', adult: false, intensity: 'wild', text: { en: 'Who here would look best after a glow-up?', fr: 'Qui serait le plus canon après un relooking ?' } },
  { id: 'p39', adult: false, intensity: 'wild', text: { en: 'Who here talks about the others behind their back the most?', fr: 'Qui parle le plus des autres dans leur dos ?' } },
  { id: 'p40', adult: false, intensity: 'wild', text: { en: 'Who here is the most jealous?', fr: 'Qui est le plus jaloux ?' } },
  { id: 'p41', adult: false, intensity: 'wild', text: { en: 'Who here has the worst temper when nobody is watching?', fr: 'Qui a le pire caractère quand personne ne regarde ?' } },
  { id: 'p42', adult: false, intensity: 'wild', text: { en: 'Who here would you least want to read your messages?', fr: 'Qui voudrais-tu le moins voir lire tes messages ?' } },
  { id: 'p43', adult: false, intensity: 'chill', text: { en: 'Who here is the most likely to become famous?', fr: 'Qui a le plus de chances de devenir célèbre ?' } },
  { id: 'p44', adult: false, intensity: 'chill', text: { en: 'Who here gives the best advice?', fr: 'Qui donne les meilleurs conseils ?' } },
  { id: 'p45', adult: false, intensity: 'chill', text: { en: 'Who here would you want on your team in a pub quiz?', fr: 'Qui voudrais-tu dans ton équipe pour un quiz ?' } },
  { id: 'p46', adult: false, intensity: 'party', text: { en: 'Who here is the worst loser?', fr: 'Qui est le plus mauvais perdant ?' } },
  { id: 'p47', adult: false, intensity: 'party', text: { en: 'Who here would be the first voted off the island?', fr: 'Qui serait éliminé en premier sur l’île ?' } },
  { id: 'p48', adult: false, intensity: 'party', text: { en: 'Who here has the most annoying laugh?', fr: 'Qui a le rire le plus agaçant ?' } },
  { id: 'p49', adult: false, intensity: 'wild', text: { en: 'Who here has the most to lose if their phone got read out?', fr: 'Qui a le plus à perdre si son téléphone était lu à voix haute ?' } },
  { id: 'p50', adult: false, intensity: 'wild', text: { en: 'Who here will still be around in twenty years?', fr: 'Qui sera encore là dans vingt ans ?' } },

  // ------------------------------------------------------------- 18+ deck ---
  { id: 'ps1', adult: true, intensity: 'wild', text: { en: 'Who here would you sleep with, no consequences?', fr: 'Avec qui coucherais-tu, sans conséquences ?' } },
  { id: 'ps2', adult: true, intensity: 'wild', text: { en: 'Who here is best in bed, purely on instinct?', fr: 'Qui est le meilleur au lit, à l’instinct ?' } },
  { id: 'ps3', adult: true, intensity: 'wild', text: { en: 'Who here has the wildest history?', fr: 'Qui a le passé le plus chaud ?' } },
  { id: 'ps4', adult: true, intensity: 'wild', text: { en: 'Who here have you thought about after a night out?', fr: 'À qui as-tu pensé après une soirée ?' } },
  { id: 'ps5', adult: true, intensity: 'wild', text: { en: 'Who here would say yes to anyone tonight?', fr: 'Qui dirait oui à n’importe qui ce soir ?' } },
  { id: 'ps6', adult: true, intensity: 'wild', text: { en: 'Who here would you never bring home to your parents?', fr: 'Qui ne présenterais-tu jamais à tes parents ?' } },
  { id: 'ps7', adult: true, intensity: 'wild', text: { en: 'Who here is faking how experienced they are?', fr: 'Qui exagère son expérience ?' } },
  { id: 'ps8', adult: true, intensity: 'wild', text: { en: 'Who here has the most secrets in their bedside drawer?', fr: 'Qui a le plus de secrets dans sa table de nuit ?' } },
];
