import type { DeckCard } from '@/games/types';

/**
 * Syllables, not translations: the English and French sides of each card are
 * independently chosen to be common in that language. Pairing them up is only
 * how the deck is stored — nobody ever sees both halves at once.
 */
export const SYLLABLES: DeckCard[] = [
  { id: 'y1', adult: false, intensity: 'chill', text: { en: 'STR', fr: 'BRE' } },
  { id: 'y2', adult: false, intensity: 'chill', text: { en: 'ING', fr: 'TION' } },
  { id: 'y3', adult: false, intensity: 'chill', text: { en: 'CON', fr: 'CON' } },
  { id: 'y4', adult: false, intensity: 'chill', text: { en: 'PRE', fr: 'PRÉ' } },
  { id: 'y5', adult: false, intensity: 'chill', text: { en: 'TION', fr: 'MENT' } },
  { id: 'y6', adult: false, intensity: 'chill', text: { en: 'ABL', fr: 'ABLE' } },
  { id: 'y7', adult: false, intensity: 'chill', text: { en: 'OUS', fr: 'EUX' } },
  { id: 'y8', adult: false, intensity: 'chill', text: { en: 'PER', fr: 'PAR' } },
  { id: 'y9', adult: false, intensity: 'chill', text: { en: 'CHE', fr: 'CHE' } },
  { id: 'y10', adult: false, intensity: 'chill', text: { en: 'SHO', fr: 'CHA' } },
  { id: 'y11', adult: false, intensity: 'chill', text: { en: 'GRA', fr: 'GRA' } },
  { id: 'y12', adult: false, intensity: 'chill', text: { en: 'TRA', fr: 'TRA' } },
  { id: 'y13', adult: false, intensity: 'chill', text: { en: 'BLE', fr: 'BLE' } },
  { id: 'y14', adult: false, intensity: 'chill', text: { en: 'MEN', fr: 'MAN' } },
  { id: 'y15', adult: false, intensity: 'chill', text: { en: 'LIS', fr: 'LIS' } },
  { id: 'y16', adult: false, intensity: 'chill', text: { en: 'ATE', fr: 'ETTE' } },
  { id: 'y17', adult: false, intensity: 'chill', text: { en: 'IST', fr: 'ISTE' } },
  { id: 'y18', adult: false, intensity: 'chill', text: { en: 'ENT', fr: 'ANT' } },
  { id: 'y19', adult: false, intensity: 'chill', text: { en: 'SUB', fr: 'SOU' } },
  { id: 'y20', adult: false, intensity: 'chill', text: { en: 'DIS', fr: 'DÉ' } },
  { id: 'y21', adult: false, intensity: 'chill', text: { en: 'FOR', fr: 'FOR' } },
  { id: 'y22', adult: false, intensity: 'chill', text: { en: 'CAR', fr: 'CAR' } },
  { id: 'y23', adult: false, intensity: 'chill', text: { en: 'MIN', fr: 'MAI' } },
  { id: 'y24', adult: false, intensity: 'chill', text: { en: 'POR', fr: 'POR' } },
  { id: 'y25', adult: false, intensity: 'chill', text: { en: 'RES', fr: 'RES' } },
  { id: 'y26', adult: false, intensity: 'chill', text: { en: 'AND', fr: 'AGE' } },
  { id: 'y27', adult: false, intensity: 'chill', text: { en: 'TER', fr: 'TER' } },
  { id: 'y28', adult: false, intensity: 'chill', text: { en: 'PLA', fr: 'PLA' } },
  { id: 'y29', adult: false, intensity: 'chill', text: { en: 'SEL', fr: 'SEL' } },
  { id: 'y30', adult: false, intensity: 'chill', text: { en: 'UND', fr: 'ONS' } },
  { id: 'y31', adult: false, intensity: 'chill', text: { en: 'ORD', fr: 'ORD' } },
  { id: 'y32', adult: false, intensity: 'chill', text: { en: 'ANC', fr: 'ANCE' } },
  { id: 'y33', adult: false, intensity: 'chill', text: { en: 'IGH', fr: 'ILL' } },
  { id: 'y34', adult: false, intensity: 'chill', text: { en: 'OUN', fr: 'OUR' } },
  { id: 'y35', adult: false, intensity: 'chill', text: { en: 'EAR', fr: 'EUR' } },
  { id: 'y36', adult: false, intensity: 'chill', text: { en: 'ROU', fr: 'ROU' } },
  { id: 'y37', adult: false, intensity: 'chill', text: { en: 'SPE', fr: 'SPÉ' } },
  { id: 'y38', adult: false, intensity: 'chill', text: { en: 'CLA', fr: 'CLA' } },
  { id: 'y39', adult: false, intensity: 'chill', text: { en: 'IVE', fr: 'IVE' } },
  { id: 'y40', adult: false, intensity: 'chill', text: { en: 'AGE', fr: 'AIS' } },
  { id: 'y41', adult: false, intensity: 'chill', text: { en: 'BAL', fr: 'BAL' } },
  { id: 'y42', adult: false, intensity: 'chill', text: { en: 'MON', fr: 'MON' } },
  { id: 'y43', adult: false, intensity: 'chill', text: { en: 'NAT', fr: 'NAT' } },
  { id: 'y44', adult: false, intensity: 'chill', text: { en: 'OVE', fr: 'OIR' } },
  { id: 'y45', adult: false, intensity: 'chill', text: { en: 'ACK', fr: 'ACHE' } },
  { id: 'y46', adult: false, intensity: 'chill', text: { en: 'ILL', fr: 'IÈRE' } },
  { id: 'y47', adult: false, intensity: 'chill', text: { en: 'UMP', fr: 'OMP' } },
  { id: 'y48', adult: false, intensity: 'chill', text: { en: 'EST', fr: 'ESTE' } },
  { id: 'y49', adult: false, intensity: 'chill', text: { en: 'AIN', fr: 'AIN' } },
  { id: 'y50', adult: false, intensity: 'chill', text: { en: 'OLD', fr: 'OLE' } },
  { id: 'y51', adult: false, intensity: 'chill', text: { en: 'SCA', fr: 'SCA' } },
  { id: 'y52', adult: false, intensity: 'chill', text: { en: 'THE', fr: 'THÉ' } },
  { id: 'y53', adult: false, intensity: 'chill', text: { en: 'WOR', fr: 'VER' } },
  { id: 'y54', adult: false, intensity: 'chill', text: { en: 'FIR', fr: 'FIN' } },
  { id: 'y55', adult: false, intensity: 'chill', text: { en: 'GHT', fr: 'GNE' } },
  { id: 'y56', adult: false, intensity: 'chill', text: { en: 'UAL', fr: 'UEL' } },
  { id: 'y57', adult: false, intensity: 'chill', text: { en: 'ITY', fr: 'ITÉ' } },
  { id: 'y58', adult: false, intensity: 'chill', text: { en: 'LOG', fr: 'LOG' } },
  { id: 'y59', adult: false, intensity: 'chill', text: { en: 'MAR', fr: 'MAR' } },
  { id: 'y60', adult: false, intensity: 'chill', text: { en: 'NIS', fr: 'NIS' } },
];
