import type { LocalizedText } from './locale.js';

/** How a game is physically played. */
export type PlayMode =
  /** One device passed around the table. */
  | 'pass'
  /** A shared host screen (TV / laptop) plus one phone per player. */
  | 'room';

export type GameCategory =
  | 'cards' // prompt / card driven
  | 'party' // classic drinking party games
  | 'spicy' // 18+ decks
  | 'skill' // reflex / dexterity mini-games
  | 'social' // bluffing, voting, guessing each other
  | 'quiz'; // knowledge & trivia

/** Rough vibe of a game, used for filtering and for the escalation engine. */
export type Intensity = 'chill' | 'party' | 'wild';

export type GameStatus = 'ready' | 'soon';

export interface GameMeta {
  id: string;
  title: LocalizedText;
  tagline: LocalizedText;
  /** Every mode this game supports. Games listing both let the player choose. */
  modes: PlayMode[];
  category: GameCategory;
  intensity: Intensity;
  /** Requires the 18+ toggle to be unlocked. */
  adult: boolean;
  minPlayers: number;
  /** null = no practical upper bound. */
  maxPlayers: number | null;
  /** Typical length in minutes, for the card badge. */
  minutes: [number, number];
  emoji: string;
  /** Tailwind-side gradient key, see web/src/lib/accents.ts */
  accent: 'violet' | 'fuchsia' | 'amber' | 'lime' | 'cyan' | 'rose' | 'orange' | 'indigo';
  status: GameStatus;
  /** Needs pen & paper, a real deck, glasses… shown as a heads-up before starting. */
  props?: LocalizedText;
}

export const GAME_CATALOGUE: GameMeta[] = [
  // ---------------------------------------------------------------- cards ---
  {
    id: 'piccolo-classic',
    title: { en: 'Piccolo Classic', fr: 'Piccolo Classique' },
    tagline: {
      en: 'The endless mixed deck. Challenges escalate as the night goes on.',
      fr: 'Le deck mélangé sans fin. Les défis montent en intensité au fil de la soirée.',
    },
    modes: ['pass'],
    category: 'cards',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: null,
    minutes: [15, 90],
    emoji: '🍸',
    accent: 'violet',
    status: 'ready',
  },
  {
    id: 'never-have-i-ever',
    title: { en: 'Never Have I Ever', fr: "Je n'ai jamais" },
    tagline: {
      en: 'Read it out. Everyone guilty drinks. Simple, ruthless.',
      fr: 'Lis à voix haute. Tous les coupables boivent. Simple, impitoyable.',
    },
    modes: ['pass'],
    category: 'cards',
    intensity: 'party',
    adult: false,
    minPlayers: 2,
    maxPlayers: null,
    minutes: [10, 40],
    emoji: '🙈',
    accent: 'fuchsia',
    status: 'ready',
  },
  {
    id: 'most-likely-to',
    title: { en: 'Most Likely To', fr: 'Le plus susceptible de' },
    tagline: {
      en: 'Point at once. Most votes drinks. Friendships optional.',
      fr: 'On pointe en même temps. Le plus voté boit. Amitiés en option.',
    },
    modes: ['pass', 'room'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: 16,
    minutes: [10, 30],
    emoji: '👉',
    accent: 'amber',
    status: 'ready',
  },
  {
    id: 'truth-or-dare',
    title: { en: 'Truth or Dare', fr: 'Action ou Vérité' },
    tagline: {
      en: 'Pick your poison. Chicken out and you drink double.',
      fr: 'Choisis ton poison. Tu te dégonfles, tu bois double.',
    },
    modes: ['pass'],
    category: 'cards',
    intensity: 'party',
    adult: false,
    minPlayers: 2,
    maxPlayers: null,
    minutes: [15, 60],
    emoji: '🎭',
    accent: 'rose',
    status: 'ready',
  },
  {
    id: 'would-you-rather',
    title: { en: 'Would You Rather', fr: 'Tu préfères' },
    tagline: {
      en: 'Two terrible options. Minority drinks.',
      fr: 'Deux options horribles. La minorité boit.',
    },
    modes: ['pass', 'room'],
    category: 'social',
    intensity: 'chill',
    adult: false,
    minPlayers: 3,
    maxPlayers: 16,
    minutes: [10, 30],
    emoji: '⚖️',
    accent: 'cyan',
    status: 'ready',
  },
  {
    id: 'paranoia',
    title: { en: 'Paranoia', fr: 'Paranoïa' },
    tagline: {
      en: 'Whisper a question, name someone out loud. They only learn why if they drink.',
      fr: 'Chuchote une question, nomme quelqu’un à voix haute. Il saura pourquoi seulement s’il boit.',
    },
    modes: ['pass'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 4,
    maxPlayers: null,
    minutes: [10, 30],
    emoji: '🤫',
    accent: 'indigo',
    status: 'ready',
  },
  {
    id: 'sip-or-spill',
    title: { en: 'Sip or Spill', fr: 'Bois ou Balance' },
    tagline: {
      en: 'Answer the question honestly, or drink and keep your secret.',
      fr: 'Réponds honnêtement, ou bois et garde ton secret.',
    },
    modes: ['pass'],
    category: 'cards',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: null,
    minutes: [10, 40],
    emoji: '🫗',
    accent: 'orange',
    status: 'ready',
  },
  {
    id: 'two-truths-a-lie',
    title: { en: 'Two Truths & a Lie', fr: 'Deux vérités, un mensonge' },
    tagline: {
      en: 'Three claims, one is fake. Wrong guessers drink.',
      fr: 'Trois affirmations, une est fausse. Les mauvais devineurs boivent.',
    },
    modes: ['pass', 'room'],
    category: 'social',
    intensity: 'chill',
    adult: false,
    minPlayers: 3,
    maxPlayers: 12,
    minutes: [15, 30],
    emoji: '🤥',
    accent: 'lime',
    status: 'ready',
  },
  {
    id: 'la-tabuses',
    title: { en: 'Là t’abuses', fr: 'Là t’abuses' },
    tagline: {
      en: 'Bid, raise, or call the bluff. Two decks: a numbers quiz, or feats you have to prove.',
      fr: 'Enchéris, surenchéris ou dénonce le bluff. Deux decks : quiz de chiffres, ou défis à prouver.',
    },
    modes: ['pass'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 2,
    maxPlayers: null,
    minutes: [10, 30],
    emoji: '🙄',
    accent: 'amber',
    status: 'ready',
  },

  // ---------------------------------------------------------------- party ---
  {
    id: 'mr-white',
    title: { en: 'Mr White', fr: 'Mr White' },
    tagline: {
      en: 'Everyone gets the same word. One gets a near miss, one gets nothing at all.',
      fr: 'Tout le monde reçoit le même mot. L’un en reçoit un presque pareil, l’autre rien du tout.',
    },
    modes: ['pass'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 4,
    maxPlayers: 16,
    minutes: [10, 30],
    emoji: '🕵️',
    accent: 'indigo',
    status: 'ready',
  },

  {
    id: 'shot-roulette',
    title: { en: 'Shot Roulette', fr: 'Roulette à shots' },
    tagline: {
      en: 'Spin the wheel of names. The wheel decides, you obey.',
      fr: 'Fais tourner la roue des noms. La roue décide, tu obéis.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'wild',
    adult: false,
    minPlayers: 2,
    maxPlayers: 16,
    minutes: [5, 20],
    emoji: '🎯',
    accent: 'rose',
    status: 'ready',
  },
  {
    id: 'kings-cup',
    title: { en: "King's Cup", fr: 'Roi des cartes' },
    tagline: {
      en: 'A full virtual deck, every card its own rule. The classic table wrecker.',
      fr: 'Un jeu de 52 cartes virtuel, une règle par carte. Le classique qui finit les tables.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'wild',
    adult: false,
    minPlayers: 3,
    maxPlayers: 12,
    minutes: [20, 60],
    emoji: '👑',
    accent: 'amber',
    status: 'ready',
    props: { en: 'One big shared glass in the middle', fr: 'Un grand verre commun au centre' },
  },
  {
    id: 'bus-ride',
    title: { en: 'The Bus Ride', fr: 'Le trajet en bus' },
    tagline: {
      en: 'Red or black, higher or lower, in or out. One loser rides the bus.',
      fr: 'Rouge ou noir, plus ou moins, dedans ou dehors. Un perdant prend le bus.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'wild',
    adult: false,
    minPlayers: 2,
    maxPlayers: 10,
    minutes: [10, 25],
    emoji: '🚌',
    accent: 'orange',
    status: 'ready',
  },
  {
    id: 'categories',
    title: { en: 'Categories', fr: 'Thèmes' },
    tagline: {
      en: 'Name something in the category. Hesitate, repeat, or blank out — drink.',
      fr: 'Cite un élément du thème. Tu hésites, tu répètes, tu bloques — tu bois.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: null,
    minutes: [10, 30],
    emoji: '🗂️',
    accent: 'cyan',
    status: 'ready',
  },
  {
    id: 'waterfall',
    title: { en: 'Waterfall', fr: 'Cascade' },
    tagline: {
      en: 'Everyone starts drinking at once. You stop only when the person before you does.',
      fr: 'Tout le monde boit en même temps. Tu t’arrêtes seulement quand celui d’avant s’arrête.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'wild',
    adult: false,
    minPlayers: 3,
    maxPlayers: 12,
    minutes: [2, 5],
    emoji: '🌊',
    accent: 'cyan',
    status: 'ready',
  },
  {
    id: 'bomb-party',
    title: { en: 'Bomb Party', fr: 'Bombe à retardement' },
    tagline: {
      en: 'A syllable, a ticking phone, pass it fast. Whoever holds it when it blows drinks.',
      fr: 'Une syllabe, un téléphone qui compte, passe vite. Celui qui l’a quand ça explose boit.',
    },
    modes: ['pass'],
    category: 'skill',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: 12,
    minutes: [5, 20],
    emoji: '💣',
    accent: 'rose',
    status: 'ready',
  },
  {
    id: 'cheers-governor',
    title: { en: 'Cheers to the Governor', fr: 'Santé au gouverneur' },
    tagline: {
      en: 'Count to 21 around the table, inventing a rule each round. Chaos guaranteed.',
      fr: 'Comptez jusqu’à 21 en inventant une règle par manche. Chaos garanti.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'wild',
    adult: false,
    minPlayers: 4,
    maxPlayers: 12,
    minutes: [10, 30],
    emoji: '🎩',
    accent: 'violet',
    status: 'ready',
  },
  {
    id: 'fingers',
    title: { en: 'Fingers', fr: 'Doigts' },
    tagline: {
      en: 'Everyone on the glass. Guess how many stay. Guess right and you are out.',
      fr: 'Tous les doigts sur le verre. Devine combien restent. Bien deviné, tu sors.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: 10,
    minutes: [5, 15],
    emoji: '🖐️',
    accent: 'lime',
    status: 'ready',
    props: { en: 'One shared glass', fr: 'Un verre commun' },
  },
  {
    id: 'medusa',
    title: { en: 'Medusa', fr: 'Méduse' },
    tagline: {
      en: 'Heads down, heads up. Eye contact means shots.',
      fr: 'Têtes baissées, têtes levées. Un regard croisé, c’est un shot.',
    },
    modes: ['pass'],
    category: 'party',
    intensity: 'wild',
    adult: false,
    minPlayers: 4,
    maxPlayers: 12,
    minutes: [5, 15],
    emoji: '🐍',
    accent: 'lime',
    status: 'ready',
  },
  {
    id: 'party-bingo',
    title: { en: 'Party Bingo', fr: 'Bingo de soirée' },
    tagline: {
      en: 'A grid of things that always happen at parties. Tick them off live.',
      fr: 'Une grille de ce qui arrive toujours en soirée. Coche en direct.',
    },
    modes: ['pass', 'room'],
    category: 'party',
    intensity: 'chill',
    adult: false,
    minPlayers: 2,
    maxPlayers: null,
    minutes: [30, 120],
    emoji: '🎫',
    accent: 'indigo',
    status: 'ready',
  },

  // ---------------------------------------------------------------- spicy ---
  {
    id: 'hot-seat',
    title: { en: 'Hot Seat', fr: 'Chaise brûlante' },
    tagline: {
      en: 'One person, sixty seconds, no mercy. Everyone asks.',
      fr: 'Une personne, soixante secondes, aucune pitié. Tout le monde interroge.',
    },
    modes: ['pass'],
    category: 'spicy',
    intensity: 'wild',
    adult: true,
    minPlayers: 3,
    maxPlayers: null,
    minutes: [10, 30],
    emoji: '🔥',
    accent: 'rose',
    status: 'ready',
  },
  {
    id: 'truth-or-dare-spicy',
    title: { en: 'Truth or Dare — Spicy', fr: 'Action ou Vérité — Épicé' },
    tagline: {
      en: 'Same rules, much less clothing-safe.',
      fr: 'Mêmes règles, beaucoup moins sage.',
    },
    modes: ['pass'],
    category: 'spicy',
    intensity: 'wild',
    adult: true,
    minPlayers: 2,
    maxPlayers: 12,
    minutes: [15, 60],
    emoji: '🌶️',
    accent: 'rose',
    status: 'ready',
  },
  {
    id: 'confessions',
    title: { en: 'Anonymous Confessions', fr: 'Confessions anonymes' },
    tagline: {
      en: 'Everyone submits a secret from their phone. Guess who wrote it.',
      fr: 'Chacun envoie un secret depuis son téléphone. Devine qui l’a écrit.',
    },
    modes: ['room'],
    category: 'spicy',
    intensity: 'wild',
    adult: true,
    minPlayers: 4,
    maxPlayers: 12,
    minutes: [15, 40],
    emoji: '🕯️',
    accent: 'indigo',
    status: 'ready',
  },
  {
    id: 'dirty-charades',
    title: { en: 'Dirty Charades', fr: 'Mimes coquins' },
    tagline: {
      en: 'Act it out. No words. Good luck explaining that one.',
      fr: 'Mime-le. Sans un mot. Bon courage pour celui-là.',
    },
    modes: ['pass'],
    category: 'spicy',
    intensity: 'wild',
    adult: true,
    minPlayers: 4,
    maxPlayers: null,
    minutes: [10, 30],
    emoji: '🙊',
    accent: 'fuchsia',
    status: 'ready',
  },

  // ---------------------------------------------------------------- skill ---
  {
    id: 'reaction-duel',
    title: { en: 'Reaction Duel', fr: 'Duel de réflexes' },
    tagline: {
      en: 'Split screen, two thumbs. Tap when it flashes — too early and you lose.',
      fr: 'Écran partagé, deux pouces. Tape quand ça flashe — trop tôt et tu perds.',
    },
    modes: ['pass'],
    category: 'skill',
    intensity: 'party',
    adult: false,
    minPlayers: 2,
    maxPlayers: 2,
    minutes: [2, 10],
    emoji: '⚡',
    accent: 'amber',
    status: 'ready',
  },
  {
    id: 'tap-battle',
    title: { en: 'Tap Battle', fr: 'Bataille de pouces' },
    tagline: {
      en: 'Five seconds. Most taps wins. Loser drinks the difference.',
      fr: 'Cinq secondes. Le plus de taps gagne. Le perdant boit la différence.',
    },
    modes: ['pass', 'room'],
    category: 'skill',
    intensity: 'party',
    adult: false,
    minPlayers: 2,
    maxPlayers: 8,
    minutes: [2, 10],
    emoji: '👍',
    accent: 'lime',
    status: 'ready',
  },
  {
    id: 'memory-chain',
    title: { en: 'Memory Chain', fr: 'Chaîne de mémoire' },
    tagline: {
      en: 'Repeat the sequence, add one. Drunk brains fail fast.',
      fr: 'Répète la séquence, ajoute-en une. Les cerveaux éméchés lâchent vite.',
    },
    modes: ['pass'],
    category: 'skill',
    intensity: 'chill',
    adult: false,
    minPlayers: 2,
    maxPlayers: 8,
    minutes: [5, 15],
    emoji: '🧠',
    accent: 'cyan',
    status: 'ready',
  },
  {
    id: 'hot-potato',
    title: { en: 'Hot Potato', fr: 'Patate chaude' },
    tagline: {
      en: 'Pass the phone while the music plays. Silence means you drink.',
      fr: 'Passe le téléphone pendant la musique. Le silence, c’est toi qui bois.',
    },
    modes: ['pass'],
    category: 'skill',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: null,
    minutes: [5, 15],
    emoji: '🥔',
    accent: 'orange',
    status: 'ready',
  },
  {
    id: 'steady-hand',
    title: { en: 'Steady Hand', fr: 'Main sûre' },
    tagline: {
      en: 'Trace the wire without touching the edges. Gets funnier every round.',
      fr: 'Suis le fil sans toucher les bords. De plus en plus drôle à chaque manche.',
    },
    modes: ['pass'],
    category: 'skill',
    intensity: 'chill',
    adult: false,
    minPlayers: 1,
    maxPlayers: 8,
    minutes: [3, 10],
    emoji: '🪡',
    accent: 'violet',
    status: 'ready',
  },
  {
    id: 'quick-math',
    title: { en: 'Quick Math', fr: 'Calcul éclair' },
    tagline: {
      en: 'Simple sums, brutal timer. Sobriety test disguised as a game.',
      fr: 'Calculs simples, chrono brutal. Un test d’alcoolémie déguisé en jeu.',
    },
    modes: ['pass'],
    category: 'skill',
    intensity: 'chill',
    adult: false,
    minPlayers: 1,
    maxPlayers: 8,
    minutes: [3, 10],
    emoji: '➗',
    accent: 'indigo',
    status: 'ready',
  },

  // ------------------------------------------------------- room / social ---
  {
    id: 'punchline',
    title: { en: 'Punchline', fr: 'Réplique' },
    tagline: {
      en: 'Fill in the blank on your phone, then vote for the funniest on the big screen.',
      fr: 'Complète la phrase sur ton téléphone, puis vote pour la plus drôle sur le grand écran.',
    },
    modes: ['room'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: 10,
    minutes: [15, 30],
    emoji: '🎤',
    accent: 'amber',
    status: 'ready',
  },
  {
    id: 'impostor',
    title: { en: 'Impostor', fr: 'Imposteur' },
    tagline: {
      en: 'Everyone gets the same secret word. Except one. Find them by how they describe it.',
      fr: 'Tout le monde reçoit le même mot secret. Sauf un. Trouve-le à sa façon de le décrire.',
    },
    modes: ['room'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 4,
    maxPlayers: 12,
    minutes: [10, 25],
    emoji: '🕵️',
    accent: 'indigo',
    status: 'ready',
  },
  {
    id: 'wavelength',
    title: { en: 'Wavelength', fr: 'Longueur d’onde' },
    tagline: {
      en: 'Hot ↔ cold, cheap ↔ classy. Give a clue, see how close the group lands.',
      fr: 'Chaud ↔ froid, cheap ↔ classe. Donne un indice, vois si le groupe te suit.',
    },
    modes: ['room'],
    category: 'social',
    intensity: 'chill',
    adult: false,
    minPlayers: 3,
    maxPlayers: 12,
    minutes: [15, 30],
    emoji: '📡',
    accent: 'cyan',
    status: 'ready',
  },
  {
    id: 'draw-and-guess',
    title: { en: 'Draw & Guess', fr: 'Dessine & devine' },
    tagline: {
      en: 'Draw on your phone, everyone guesses on the TV. Terrible art encouraged.',
      fr: 'Dessine sur ton téléphone, tout le monde devine sur la télé. Art moche encouragé.',
    },
    modes: ['room'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: 10,
    minutes: [15, 30],
    emoji: '🎨',
    accent: 'fuchsia',
    status: 'ready',
  },
  {
    id: 'liar-liar',
    title: { en: 'Liar Liar', fr: 'Menteur' },
    tagline: {
      en: 'Obscure trivia. Invent a convincing wrong answer and farm your friends.',
      fr: 'Anecdotes obscures. Invente une fausse réponse crédible et piège tes amis.',
    },
    modes: ['room'],
    category: 'quiz',
    intensity: 'party',
    adult: false,
    minPlayers: 3,
    maxPlayers: 10,
    minutes: [15, 35],
    emoji: '🃏',
    accent: 'rose',
    status: 'ready',
  },
  {
    id: 'rank-it',
    title: { en: 'Rank It', fr: 'Classe-les' },
    tagline: {
      en: 'Rank five things privately. Score points for matching the group.',
      fr: 'Classe cinq choses en secret. Marque des points en collant au groupe.',
    },
    modes: ['room'],
    category: 'social',
    intensity: 'chill',
    adult: false,
    minPlayers: 3,
    maxPlayers: 12,
    minutes: [10, 25],
    emoji: '🏅',
    accent: 'lime',
    status: 'ready',
  },
  {
    id: 'who-in-the-room',
    title: { en: 'Who In The Room', fr: 'Qui dans la pièce' },
    tagline: {
      en: 'Anonymous voting on superlatives, results revealed one savage card at a time.',
      fr: 'Vote anonyme sur des superlatifs, résultats révélés une carte cruelle à la fois.',
    },
    modes: ['room'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 4,
    maxPlayers: 16,
    minutes: [10, 25],
    emoji: '🗳️',
    accent: 'violet',
    status: 'ready',
  },
  {
    id: 'trivia-night',
    title: { en: 'Trivia Night', fr: 'Quiz de soirée' },
    tagline: {
      en: 'Buzzer rounds on the host screen, four answers on every phone.',
      fr: 'Manches au buzzer sur l’écran hôte, quatre réponses sur chaque téléphone.',
    },
    modes: ['room'],
    category: 'quiz',
    intensity: 'chill',
    adult: false,
    minPlayers: 2,
    maxPlayers: 16,
    minutes: [15, 40],
    emoji: '❓',
    accent: 'amber',
    status: 'ready',
  },
  {
    id: 'werewolf-express',
    title: { en: 'Werewolf Express', fr: 'Loup-garou express' },
    tagline: {
      en: 'Roles dealt to phones, no narrator needed. Ten minute rounds.',
      fr: 'Rôles distribués aux téléphones, sans narrateur. Manches de dix minutes.',
    },
    modes: ['room'],
    category: 'social',
    intensity: 'party',
    adult: false,
    minPlayers: 5,
    maxPlayers: 16,
    minutes: [10, 25],
    emoji: '🐺',
    accent: 'orange',
    status: 'ready',
  },
];

export const GAME_BY_ID: Record<string, GameMeta> = Object.fromEntries(
  GAME_CATALOGUE.map((g) => [g.id, g]),
);

export function getGame(id: string): GameMeta | undefined {
  return GAME_BY_ID[id];
}
