import type { DeckCard } from '@/games/types';

/**
 * A category has to be wide enough that ten people can each name one, and
 * narrow enough that the eleventh cannot. Everything here has been sanity
 * checked against "could a drunk person think of five?".
 */
export const CATEGORY_DECK: DeckCard[] = [
  { id: 'k1', adult: false, intensity: 'chill', text: { en: 'Car brands', fr: 'Marques de voitures' } },
  { id: 'k2', adult: false, intensity: 'chill', text: { en: 'Pizza toppings', fr: 'Garnitures de pizza' } },
  { id: 'k3', adult: false, intensity: 'chill', text: { en: 'Countries in Europe', fr: 'Pays d’Europe' } },
  { id: 'k4', adult: false, intensity: 'chill', text: { en: 'Things in a kitchen drawer', fr: 'Objets dans un tiroir de cuisine' } },
  { id: 'k5', adult: false, intensity: 'chill', text: { en: 'Football clubs', fr: 'Clubs de football' } },
  { id: 'k6', adult: false, intensity: 'chill', text: { en: 'Breakfast foods', fr: 'Aliments du petit-déjeuner' } },
  { id: 'k7', adult: false, intensity: 'chill', text: { en: 'Disney films', fr: 'Films Disney' } },
  { id: 'k8', adult: false, intensity: 'chill', text: { en: 'Things that are cold', fr: 'Choses froides' } },
  { id: 'k9', adult: false, intensity: 'chill', text: { en: 'Board games', fr: 'Jeux de société' } },
  { id: 'k10', adult: false, intensity: 'chill', text: { en: 'Words that rhyme with "night"', fr: 'Mots qui riment avec « nuit »' } },
  { id: 'k11', adult: false, intensity: 'chill', text: { en: 'Animals bigger than a dog', fr: 'Animaux plus gros qu’un chien' } },
  { id: 'k12', adult: false, intensity: 'chill', text: { en: 'Colours that are not primary', fr: 'Couleurs qui ne sont pas primaires' } },
  { id: 'k13', adult: false, intensity: 'chill', text: { en: 'Capital cities', fr: 'Capitales' } },
  { id: 'k14', adult: false, intensity: 'chill', text: { en: 'Superheroes', fr: 'Super-héros' } },
  { id: 'k15', adult: false, intensity: 'chill', text: { en: 'Things in this room', fr: 'Objets dans cette pièce' } },
  { id: 'k16', adult: false, intensity: 'chill', text: { en: 'Types of cheese', fr: 'Sortes de fromage' } },
  { id: 'k17', adult: false, intensity: 'chill', text: { en: 'Musical instruments', fr: 'Instruments de musique' } },
  { id: 'k18', adult: false, intensity: 'chill', text: { en: 'Jobs your parents would approve of', fr: 'Métiers que tes parents approuveraient' } },
  { id: 'k19', adult: false, intensity: 'chill', text: { en: 'Fruits that are not apples', fr: 'Fruits qui ne sont pas des pommes' } },
  { id: 'k20', adult: false, intensity: 'chill', text: { en: 'Streaming series everyone has seen', fr: 'Séries que tout le monde a vues' } },
  { id: 'k21', adult: false, intensity: 'chill', text: { en: 'Things in a first aid kit', fr: 'Choses dans une trousse de secours' } },
  { id: 'k22', adult: false, intensity: 'chill', text: { en: 'Cities you could get to by train', fr: 'Villes accessibles en train' } },
  { id: 'k23', adult: false, intensity: 'chill', text: { en: 'Board game pieces', fr: 'Pièces de jeux de société' } },
  { id: 'k24', adult: false, intensity: 'chill', text: { en: 'Words with a double letter', fr: 'Mots avec une lettre doublée' } },
  { id: 'k25', adult: false, intensity: 'party', text: { en: 'Cocktails', fr: 'Cocktails' } },
  { id: 'k26', adult: false, intensity: 'party', text: { en: 'Beer brands', fr: 'Marques de bière' } },
  { id: 'k27', adult: false, intensity: 'party', text: { en: 'Excuses for being late', fr: 'Excuses pour un retard' } },
  { id: 'k28', adult: false, intensity: 'party', text: { en: 'Reasons to leave a party early', fr: 'Raisons de partir tôt d’une soirée' } },
  { id: 'k29', adult: false, intensity: 'party', text: { en: 'Songs everyone knows the chorus of', fr: 'Chansons dont tout le monde connaît le refrain' } },
  { id: 'k30', adult: false, intensity: 'party', text: { en: 'Things you should not say to your boss', fr: 'Choses à ne pas dire à son patron' } },
  { id: 'k31', adult: false, intensity: 'party', text: { en: 'Hangover cures', fr: 'Remèdes contre la gueule de bois' } },
  { id: 'k32', adult: false, intensity: 'party', text: { en: 'Bad tattoo ideas', fr: 'Mauvaises idées de tatouage' } },
  { id: 'k33', adult: false, intensity: 'party', text: { en: 'Things you find in a taxi at 4am', fr: 'Choses trouvées dans un taxi à 4 h' } },
  { id: 'k34', adult: false, intensity: 'party', text: { en: 'Ways to lose a phone', fr: 'Façons de perdre un téléphone' } },
  { id: 'k35', adult: false, intensity: 'party', text: { en: 'Dating app red flags', fr: 'Red flags sur les applis de rencontre' } },
  { id: 'k36', adult: false, intensity: 'party', text: { en: 'Things that ruin a photo', fr: 'Choses qui gâchent une photo' } },
  { id: 'k37', adult: false, intensity: 'party', text: { en: 'Ways to embarrass yourself in public', fr: 'Façons de se ridiculiser en public' } },
  { id: 'k38', adult: false, intensity: 'party', text: { en: 'Things people lie about on a CV', fr: 'Mensonges classiques sur un CV' } },
  { id: 'k39', adult: false, intensity: 'party', text: { en: 'Snacks worth getting out of bed for', fr: 'Snacks qui valent de sortir du lit' } },
  { id: 'k40', adult: false, intensity: 'party', text: { en: 'Nicknames for someone at this table', fr: 'Surnoms pour quelqu’un à cette table' } },
  { id: 'k41', adult: false, intensity: 'party', text: { en: 'Terrible first date locations', fr: 'Pires lieux pour un premier rendez-vous' } },
  { id: 'k42', adult: false, intensity: 'party', text: { en: 'Things you have googled at 3am', fr: 'Choses cherchées sur Google à 3 h du matin' } },
  { id: 'k43', adult: false, intensity: 'party', text: { en: 'Songs to cry to', fr: 'Chansons pour pleurer' } },
  { id: 'k44', adult: false, intensity: 'party', text: { en: 'Words that sound rude but are not', fr: 'Mots qui sonnent vulgaires mais ne le sont pas' } },
  { id: 'k45', adult: false, intensity: 'party', text: { en: 'Reasons to text someone at midnight', fr: 'Raisons d’écrire à quelqu’un à minuit' } },
  { id: 'k46', adult: false, intensity: 'party', text: { en: 'Bad haircuts', fr: 'Mauvaises coupes de cheveux' } },
  { id: 'k47', adult: false, intensity: 'party', text: { en: 'Things that are overrated', fr: 'Choses surestimées' } },
  { id: 'k48', adult: false, intensity: 'party', text: { en: 'Ways to get out of a conversation', fr: 'Façons d’échapper à une conversation' } },
  { id: 'k49', adult: false, intensity: 'wild', text: { en: 'Things you would never tell your mother', fr: 'Choses que tu ne dirais jamais à ta mère' } },
  { id: 'k50', adult: false, intensity: 'wild', text: { en: 'Reasons a friendship ends', fr: 'Raisons pour lesquelles une amitié s’arrête' } },
  { id: 'k51', adult: false, intensity: 'wild', text: { en: 'Lies you have told tonight', fr: 'Mensonges dits ce soir' } },
  { id: 'k52', adult: false, intensity: 'wild', text: { en: 'Things worth ending a relationship over', fr: 'Raisons valables de rompre' } },
  { id: 'k53', adult: false, intensity: 'wild', text: { en: 'Secrets people in this room might have', fr: 'Secrets que les gens ici pourraient avoir' } },
  { id: 'k54', adult: false, intensity: 'wild', text: { en: 'Things you regret buying', fr: 'Achats que tu regrettes' } },
  { id: 'k55', adult: false, intensity: 'wild', text: { en: 'Worst things to shout in a quiet room', fr: 'Pires choses à crier dans une salle silencieuse' } },
  { id: 'k56', adult: false, intensity: 'chill', text: { en: 'Things that are round', fr: 'Choses rondes' } },
  { id: 'k57', adult: false, intensity: 'chill', text: { en: 'Sports played with a ball', fr: 'Sports avec un ballon' } },
  { id: 'k58', adult: false, intensity: 'chill', text: { en: 'Famous people called by one name', fr: 'Célébrités connues par un seul nom' } },
  { id: 'k59', adult: false, intensity: 'chill', text: { en: 'Things in a suitcase', fr: 'Choses dans une valise' } },
  { id: 'k60', adult: false, intensity: 'chill', text: { en: 'Video games', fr: 'Jeux vidéo' } },
  { id: 'k61', adult: false, intensity: 'chill', text: { en: 'Things that need batteries', fr: 'Objets qui ont besoin de piles' } },
  { id: 'k62', adult: false, intensity: 'party', text: { en: 'Phrases used by someone lying', fr: 'Phrases utilisées par un menteur' } },
  { id: 'k63', adult: false, intensity: 'party', text: { en: 'Bad party gifts', fr: 'Mauvais cadeaux de soirée' } },
  { id: 'k64', adult: false, intensity: 'chill', text: { en: 'Words with no good translation', fr: 'Mots sans bonne traduction' } },

  // ------------------------------------------------------------- 18+ deck ---
  { id: 'ks1', adult: true, intensity: 'wild', text: { en: 'Places you should not hook up', fr: 'Endroits où il ne faut pas coucher' } },
  { id: 'ks2', adult: true, intensity: 'wild', text: { en: 'Pick-up lines that should be illegal', fr: 'Phrases de drague qui devraient être interdites' } },
  { id: 'ks3', adult: true, intensity: 'wild', text: { en: 'Things found in a bedside drawer', fr: 'Choses trouvées dans une table de nuit' } },
  { id: 'ks4', adult: true, intensity: 'wild', text: { en: 'Euphemisms for sex', fr: 'Euphémismes pour le sexe' } },
  { id: 'ks5', adult: true, intensity: 'wild', text: { en: 'Reasons a hookup goes wrong', fr: 'Raisons pour lesquelles un coup d’un soir foire' } },
  { id: 'ks6', adult: true, intensity: 'wild', text: { en: 'Body parts, but be polite about it', fr: 'Parties du corps, mais restez polis' } },
];
